- korge/src/commonMain/kotlin/com/soywiz/korge/view/Text.kt
Let's add a `color` param to the `Container.text(...)`. So we can change the color of texts.
> Add color param to Text View

- korge/src/commonMain/kotlin/com/soywiz/korge/view/RectBase.kt
Related issue: 
https://github.com/korlibs/korge/issues/40
> Updated rendering order in RectBase.kt

- korge-box2d/src/commonMain/kotlin/com.soywiz.korge.box2d/Box2d.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/render/BatchBuilder2D.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/render/DebugLineRenderContext.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/render/RenderContext.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/render/RenderContext2D.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/Image.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/RectBase.kt
Box2D improvements:
- Documentation for WorldView and classes
- New createSimpleBody
- RectBase.anchor, center and centered extensions
- Allow to debug views printing lines around shapes
Korge improvements:
- RenderContext plugable generic flusher
- New DebugLineRenderContext (RenderContext.debugLineRenderContext) allowing to draw lines
> Box2D and Korge improvements

- korge-box2d/src/commonMain/kotlin/com.soywiz.korge.box2d/Box2d.kt
Added to Worldview because its a view operation
> Added pixel and world conversion functions to WorldView

- korge/src/commonMain/kotlin/com/soywiz/korge/scene/Scene.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/scene/SceneContainer.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/scene/Transition.kt
> Some work documenting [Scene]

- korge/src/commonMain/kotlin/com/soywiz/korge/animate/Animator.kt
- Add `sequenceLazy` and `parallelLazy` functions, whose callbacks are executed just before their Animator's animations are launched.
- Add `AnimatorDslMarker` and mark animation functions with it.
> Add lazy-evaluated animation, add AnimatorDslMarker

- korge/src/commonMain/kotlin/com/soywiz/korge/view/View.kt
Add extension functions for View:
- centerXBetween(x1, x2)
- centerYBetween(y1, y2)
- centerBetween(x1, y1, x2, y2)
- centerXBy(other: View)
- centerYBy(other: View)
- centerBy(other: VIew)
> Implement centering for views

- korge-dragonbones/src/commonTest/kotlin/SkipIOTest.kt
- korge-dragonbones/src/commonTest/kotlin/com/dragonbones/parser/DataParserTest.kt
- korge-dragonbones/src/commonTest/kotlin/com/dragonbones/parser/KorgeDbViewsTest.kt
- korge-swf/src/commonTest/kotlin/SkipIOTest.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/input/DragComponent.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/input/MouseEvents.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/input/SwipeComponent.kt
- korge/src/commonTest/kotlin/SkipIOTest.kt
- korge/src/commonTest/kotlin/com/soywiz/korge3d/test.kt
Add SwipeComponent (actually, just `onSwipe` function) that lets you define action when swipes are performed. It lets you specify an optional threshold, after which a swipe should be triggered, and an optional direction for swipes (all directions by default).
Also deprecate DragComponent with indication of using `onMouseDrag` instead.
> Implement SwipeComponent

- korge/src/commonMain/kotlin/com/soywiz/korge/Korge.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/tests/ViewsForTesting.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/Stage.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/Views.kt
This is a temporal workaround. This delays the execution of the main entrypoint just before the first frame. But we can and should do better later by simplifying some stuff at the korgw level.
> Fixes #112 : initial size of the Stage was wrong

- korge/src/commonMain/kotlin/com/soywiz/korge/view/Sprite.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/SpriteAnimation.kt
For a sample how to use it see PR from korge-samples:
https://github.com/korlibs/korge-samples/pull/13
> Added SpriteAnimation.kt

- korge/src/commonMain/kotlin/com/soywiz/korge/view/Sprite.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/SpriteAnimation.kt
- Fixed animation playing only one frame when one cycle was requested
- Added possibility to reverse animation
- Added startFrameIndex to start at a certain animationpoint
- Added showBitmapAtIndex to switch animationphases manually
- Added possibility to just call playAnimation() -> default animation (when provided) is played. Nothing happens when no Animation is specified
> Fixes and additions

- korge/src/commonMain/kotlin/com/soywiz/korge/render/AgBitmapTextureManager.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/render/BatchBuilder2D.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/tiles/TileMap.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/tiles/TileSet.kt
- korge/src/commonTest/kotlin/com/soywiz/korge/tiled/TiledMapTest.kt
> Support multiples textures in TileSet + TileMap optimizations. Fixes #160

- korge/src/commonMain/kotlin/com/soywiz/korge/view/Sprite.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/SpriteAnimation.kt
- Removed redundant _playAnimation()_
- Fixed bug where multiline SpriteMaps were not read correctly
> Fixes vor SpriteAnimations

- korge/src/commonMain/kotlin/com/soywiz/korge/render/BatchBuilder2D.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/render/RenderContext.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/render/VertexInfo.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/Text.kt
- korge/src/commonTest/kotlin/com/soywiz/korge/view/TextTest.kt
As shortcuts to simplify using the Html.Format
> Fixes #182 - Adds Text.textSize, Text.font and Text.color properties

- korge/src/commonMain/kotlin/com/soywiz/korge/Korge.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/tests/ViewsForTesting.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/Circle.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/Sprite.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/SpriteAnimation.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/Views.kt
- korge/src/commonTest/kotlin/com/soywiz/korge/view/SpritesTest.kt
- korge/src/jvmTest/kotlin/com/soywiz/korge/view/ViewsJvmTest.kt
> Add end frame for sprite animations

- korge/src/commonMain/kotlin/com/soywiz/korge/animate/Animator.kt
It's useful when you need to loop several groups of tween animations that last different amounts of time.
Before this PR:
```
launchImmediately {
while (true) animateSequence {
tween(wave::time[1.seconds], time = 2.seconds, easing = Easing.EASE_IN_OUT)
tween(wave::time[0.seconds], time = 2.seconds, easing = Easing.EASE_IN_OUT)
}
}
launchImmediately {
while (true) animateSequence {
tween(blur::radius[16], time = 3.seconds, easing = Easing.EASE_IN_OUT)
tween(blur::radius[0], time = 3.seconds, easing = Easing.EASE_IN_OUT)
}
}
```
With this PR:
```
animateParallel {
sequence(looped = true) {
tween(wave::time[1.seconds], time = 2.seconds, easing = Easing.EASE_IN_OUT)
tween(wave::time[0.seconds], time = 2.seconds, easing = Easing.EASE_IN_OUT)
}
sequence(looped = true) {
tween(blur::radius[16], …
```
> Support looped tween animation

- korge-swf/src/commonMain/kotlin/com/soywiz/korge/ext/swf/AtlasFactory.kt
- korge-swf/src/commonMain/kotlin/com/soywiz/korge/ext/swf/SwfLoaderMethod.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/atlas/AtlasPacker.kt
- korge/src/jvmMain/kotlin/com/soywiz/korge/atlas/AtlasResourceProcessor.kt
> Initial atlas border expansion on SWF

- gradle.properties
- korge/src/commonMain/kotlin/com/soywiz/korge/Korge.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/scene/Scene.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/scene/SceneContainer.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/tests/ViewsForTesting.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/Views.kt
- korge/src/commonTest/kotlin/com/soywiz/korge/view/ViewsInjectorTest.kt
#246: Use korinject withInjector in korge entry point + scenes with the child injector
> Implements #246: Allow to get the current injector from any suspend function

- korge/src/commonMain/kotlin/com/soywiz/korge/view/Graphics.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/View.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/ViewCollision.kt
- korge/src/commonTest/kotlin/com/soywiz/korge/view/GraphicsTest.kt
> Ensure that two intersection shapes in Graphics doesn't produce the right hitTest

- korge/src/commonMain/kotlin/com/soywiz/korge/view/ClipContainer.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/FixedSizeContainer.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/Views.kt
- korge/src/commonTest/kotlin/com/soywiz/korge/view/ViewFixedSizeContainerTest.kt
Were in global coordinates, not in window coordinates.
Fixes #256
> Fix scissors computed for FixedSizeContainer/ClipContainer

- .github/workflows/DEPLOY.yml
For testing this live in the repo (KorGE) which is frequently changed.Should not affect deployment or publishing on bintray because it runs after publish-finalize task
> ⚙️ Added sync with central versioning repo to DEPLOY.yml

- gradle.properties
- korge/src/commonMain/kotlin/com/soywiz/korge/input/MouseEvents.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/FpsOverlay.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/Views.kt
> Fix overlay proposal

- korge/src/commonMain/kotlin/com/soywiz/korge3d/format/Collada.kt
- korge/src/commonTest/kotlin/com/soywiz/korge3d/ColladaTest.kt
- korge/src/commonTest/resources/animations_flat.dae
- korge/src/commonTest/resources/animations_nested.dae
Fixes #308. See commit messages of individual commits for details.
> Fix COLLADA nested animations parsing

- korge/src/commonMain/kotlin/com/soywiz/korge/ui/UIComboBox.kt
Partial fix for UIComboBox where the itemsList would cover underlying controls even when hidden
https://github.com/korlibs/korgw/issues/40
> Partial fix for UIComboBox

- korio/src/commonMain/kotlin/com/soywiz/korio/lang/Charset.kt
- korio/src/commonTest/kotlin/com/soywiz/korio/lang/CharsetTest.kt
Some work on https://github.com/korlibs/korge/issues/794
> Implement Charset.forName

- korio/src/commonMain/kotlin/com/soywiz/korio/lang/Charset.kt
- korio/src/jsMain/kotlin/com/soywiz/korio/lang/CharsetJs.kt
- korio/src/jsMain/kotlin/com/soywiz/korio/lang/UTF8.kt
- korio/src/jsTest/kotlin/com/soywiz/korio/lang/CharsetJsTest.kt
- korio/src/jvmAndroidMain/kotlin/com/soywiz/korio/lang/CharsetJvm.kt
- korio/src/jvmTest/kotlin/com/soywiz/korio/lang/CharsetJvmTest.kt
- korio/src/nativeMain/kotlin/com/soywiz/korio/lang/CharsetNative.kt
Fixes https://github.com/korlibs/korge/issues/794
> Support JVM & JS platform native Charset encoders/decoders

- korau/src/commonMain/kotlin/com/soywiz/korau/format/mp3/minimp3/BaseMinimp3AudioFormat.kt
- korau/src/commonMain/kotlin/com/soywiz/korau/format/mp3/minimp3/Minimp3AudioFormat.kt
- korau/src/commonMain/kotlin/com/soywiz/korau/sound/Sound.kt
- korau/src/commonMain/kotlin/com/soywiz/korau/sound/SoundAudioStream.kt
- korau/src/commonTest/kotlin/com.soywiz.korau.sound/SoundAudioStreamTest.kt
- korau/src/nativeMain/kotlin/com/soywiz/korau/sound/NativeAudioDecoder.kt
- korge-sandbox/src/commonMain/kotlin/samples/MainSound.kt
Fixes https://github.com/korlibs/korge/issues/793
> Fixes SoundAudioStream.SoundChannel.current and fixes getting mp3 length based on LAME Xing/Info tags

- korge/src/commonMain/kotlin/com/soywiz/korge/animate/serialization/AnLibrarySerializer.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/BlendMode.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/View.kt
Relatest to https://github.com/korlibs/korge/issues/827
> Support custom BlendMode

- korge-sandbox/src/commonMain/kotlin/Main.kt
- korge-sandbox/src/commonMain/kotlin/samples/MainSuspendUserInput.kt
Proposal for https://github.com/korlibs/korge/issues/873
> Sample showing how to wait and handle several kind of user interaction using suspending functions

- korge-sandbox/src/commonMain/kotlin/Main.kt
- korge-sandbox/src/commonMain/kotlin/samples/MainSDF.kt
- korgw/src/commonMain/kotlin/com/soywiz/korag/gl/AGQueueProcessorOpenGL.kt
Info on SDFs:
https://iquilezles.org/articles/distfunctions2d/
> Show how to use SDF with custom views

- buildSrc/src/main/resources/index.v2.template.html
- korge/src/commonMain/kotlin/com/soywiz/korge/text/TextEditController.kt
- korgw/src/jsMain/kotlin/com/soywiz/korgw/DefaultGameWindowJs.kt
* Fixes https://github.com/korlibs/korge/issues/880
* Fixes https://github.com/korlibs/korge/issues/493
> Supports text input in HTML Mobile

- kmem/src/commonMain/kotlin/com/soywiz/kmem/Numbers.kt
- korge-sandbox/src/commonMain/kotlin/Main.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/animation/ParallaxDataView.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/tiles/TileMap.kt
- korim/src/commonMain/kotlin/com/soywiz/korim/color/CMYK.kt
- korim/src/commonMain/kotlin/com/soywiz/korim/color/RGBA.kt
- korim/src/commonMain/kotlin/com/soywiz/korim/color/YCbCr.kt
- korim/src/commonMain/kotlin/com/soywiz/korim/color/YUVA.kt
- korim/src/commonMain/kotlin/com/soywiz/korim/internal/ClampExt.kt
- korim/src/commonMain/kotlin/com/soywiz/korim/internal/MathExt.kt
- korim/src/commonMain/kotlin/com/soywiz/korim/vector/CompositeOperation.kt
- korma/build.gradle
- korma/src/commonMain/kotlin/com/soywiz/korma/geom/IRectangle.kt
- korma/src/commonMain/kotlin/com/soywiz/korma/geom/Line.kt
- korma/src/commonMain/kotlin/com/soywiz/korma/geom/Point.kt
- korma/src/commonMain/kotlin/com/soywiz/korma/geom/PointPool.kt
- korma/src/commonMain/kotlin/com/soywiz/korma/geom/bezier/BezierOld.kt
- korma/src/commonMain/kotlin/com/soywiz/korma/geom/bezier/CurvesToStroke.kt
- korma/src/commonMain/kotlin/com/soywiz/korma/geom/vector/StrokeToFill.kt
- korma/src/commonMain/kotlin/com/soywiz/korma/interpolation/Easing.kt
- korma/src/commonMain/kotlin/com/soywiz/korma/math/Math.kt
- korma/src/commonTest/kotlin/com/soywiz/korma/math/MathTest.kt
Fixes https://github.com/korlibs/korge/issues/478
> Move all clamping to kmem and remove the ones from korma

- korge/src/commonMain/kotlin/com/soywiz/korge/view/BaseGraphics.kt
- korge/src/commonTest/kotlin/com/soywiz/korge/view/GraphicsTest.kt
Fixes https://github.com/korlibs/korge/issues/433
> Fixes CpuGraphics positioning with strokes

- korge/src/commonMain/kotlin/com/soywiz/korge/view/NinePatchEx.kt
- korge/src/commonTest/kotlin/com/soywiz/korge/view/NinePatchTest.kt
Fixes https://github.com/korlibs/korge/issues/872
> Fixes NinePatch not updating on color/alpha changes

- korma/src/commonMain/kotlin/com/soywiz/korma/geom/vector/VectorBuilder.kt
- korma/src/commonTest/kotlin/com/soywiz/korma/geom/vector/VectorBuilderTest.kt
> Supports constructing parallelogram vector paths

- klock/src/commonMain/kotlin/com/soywiz/klock/DateFormat.kt
- klock/src/commonMain/kotlin/com/soywiz/klock/DateTime.kt
- klock/src/commonMain/kotlin/com/soywiz/klock/wrapped/WDateTime.kt
- klock/src/commonTest/kotlin/com/soywiz/klock/DateTimeTest.kt
- klock/src/commonTest/kotlin/com/soywiz/klock/KlockTest.kt
- klock/src/commonTest/kotlin/com/soywiz/klock/SimplerDateFormatTest.kt
- klock/src/jvmTest/kotlin/com/soywiz/klock/KlockInternalTest.kt
- korio/src/commonMain/kotlin/com/soywiz/korio/file/std/CatalogVfs.kt
- korio/src/commonMain/kotlin/com/soywiz/korio/file/std/MapLikeStorageVfs.kt
- korio/src/commonTest/kotlin/com/soywiz/korio/vfs/MapLikeStorageVfsTest.kt
- korio/src/jvmAndroidMain/kotlin/com/soywiz/korio/file/std/BaseLocalVfsJvm.kt
> Create new methods which detail the unix unit for time apis and add deprecation annotations to prefer the new methods.

- korge-sandbox/src/commonMain/kotlin/Main.kt
- korge-sandbox/src/commonMain/kotlin/samples/MainVectorNinePatch.kt
- korim/src/commonMain/kotlin/com/soywiz/korim/util/NinePatchSlices.kt
- korim/src/commonMain/kotlin/com/soywiz/korim/util/NinePatchSlices2D.kt
- korim/src/commonMain/kotlin/com/soywiz/korim/vector/NinePatchVector.kt
- korim/src/commonTest/kotlin/com/soywiz/korim/util/NinePatchToolsTest.kt
- korim/src/commonTest/kotlin/com/soywiz/korim/vector/NinePatchVectorTest.kt
- korma/src/commonMain/kotlin/com/soywiz/korma/geom/range/OpenRange.kt
Misses scaling down, and support for filled/stroked shapes
> Added NinePatchVector

- korio/src/androidMain/kotlin/com/soywiz/korio/file/std/StandardBasePathsAndroid.kt
- korio/src/commonMain/kotlin/com/soywiz/korio/file/std/StandardPathsBase.kt
- korio/src/commonTest/kotlin/com/soywiz/korio/file/std/StandardPathsTest.kt
- korio/src/darwinMain/kotlin/com/soywiz/korio/file/std/StandardBasePathsDarwin.kt
- korio/src/iosMain/kotlin/com/soywiz/korio/file/std/StandardBasePathsIos.kt
- korio/src/jsMain/kotlin/com/soywiz/korio/file/std/StandardBasePathsJs.kt
- korio/src/jsMain/kotlin/com/soywiz/korio/runtime/node/JsRuntimeNode.kt
- korio/src/jvmAndroidMain/kotlin/com/soywiz/korio/file/std/StandardPathsJvmAndroid.kt
- korio/src/jvmMain/kotlin/com/soywiz/korio/file/std/StandardBasePathsJvm.kt
- korio/src/linuxMain/kotlin/com/soywiz/korio/cwd.kt
- korio/src/linuxMain/kotlin/com/soywiz/korio/file/std/StandardBasePathsJs.kt
- korio/src/macosMain/kotlin/com/soywiz/korio/file/std/StandardBasePathsMacos.kt
- korio/src/mingwMain/kotlin/com/soywiz/korio/file/std/StandardBasePathsMingw.kt
- korio/src/mingwMain/kotlin/com/soywiz/korio/posix/PosixExtMingw.kt
- korio/src/nativeMain/kotlin/com/soywiz/korio/file/std/LocalVfsNative.kt
- korio/src/nativeMain/kotlin/com/soywiz/korio/file/std/StandardBasePathsNative.kt
- korio/src/nativeMain/kotlin/com/soywiz/korio/posix/PosixExtExpect.kt
- korio/src/posixInteropMain/kotlin/com/soywiz/korio/posix/PosixExtPosix.kt
Some work on https://github.com/korlibs/korge/issues/1000
> Expose standard paths & adjust standard vfs with them

- kds/src/commonMain/kotlin/com/soywiz/kds/ChunkedByteDeque.kt
- kds/src/commonMain/kotlin/com/soywiz/kds/Pool.kt
- kds/src/commonMain/kotlin/com/soywiz/kds/algo/Historiogram.kt
- kds/src/commonMain/kotlin/com/soywiz/kds/lock/Lock.kt
- kds/src/commonMain/kotlin/com/soywiz/kds/sync/SynchronizedCollection.kt
- kds/src/commonMain/kotlin/com/soywiz/kds/sync/SynchronizedList.kt
- kds/src/commonMain/kotlin/com/soywiz/kds/sync/SynchronizedMap.kt
- kds/src/commonMain/kotlin/com/soywiz/kds/sync/SynchronizedMutableIterator.kt
- kds/src/commonMain/kotlin/com/soywiz/kds/sync/SynchronizedSet.kt
- kds/src/jsMain/kotlin/com/soywiz/kds/lock/LockJs.kt
- kds/src/jvmAndroidMain/kotlin/com/soywiz/kds/lock/LockJvm.kt
- kds/src/nativeMain/kotlin/com/soywiz/kds/lock/LockNative.kt
- korau/src/commonMain/kotlin/com/soywiz/korau/sound/PlatformAudioOutput.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/tests/TestCoroutineDispatcher.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/tests/ViewsForTesting.kt
- korgw/src/androidMain/kotlin/com/soywiz/korgw/KorgwSurfaceView.kt
- korgw/src/commonMain/kotlin/com/soywiz/korag/AGList.kt
- korgw/src/commonMain/kotlin/com/soywiz/korag/gl/AGOpengl.kt
- korgw/src/commonMain/kotlin/com/soywiz/korag/log/LogAG.kt
- korgw/src/commonMain/kotlin/com/soywiz/korgw/GameWindow.kt
- korgw/src/commonMain/kotlin/com/soywiz/korgw/TouchEventHandler.kt
- korgw/src/commonTest/kotlin/com/soywiz/korag/AGListTest.kt
- korim/src/commonMain/kotlin/com/soywiz/korim/format/ImageFormatsMutable.kt
- korio/src/commonMain/kotlin/com/soywiz/korio/async/AsyncQueue.kt
- korio/src/commonMain/kotlin/com/soywiz/korio/lang/Charset.kt
- korio/src/commonTest/kotlin/com/soywiz/korio/concurrent/LockTest.kt
Fixes https://github.com/korlibs/korge/issues/1014
> Optimises AGList writing and reading

- kmem/src/commonMain/kotlin/com/soywiz/kmem/Platform.kt
- korio/src/commonMain/kotlin/com/soywiz/korio/util/OS.kt
- korio/src/commonTest/kotlin/com/soywiz/korio/net/AsyncClientServerTest.kt
- korio/src/jsMain/kotlin/com/soywiz/korio/runtime/node/JsRuntimeNode.kt
Fixes https://github.com/korlibs/korge/issues/1019
> Fix NodeJsAsyncClient, implements NodeJsAsyncServer, and run AsyncClientServerTest in nodeJS too

- korgw/src/androidMain/kotlin/com/soywiz/korgw/DefaultGameWindowAndroid.kt
- korgw/src/commonMain/kotlin/com/soywiz/korgw/GameWindow.kt
- korgw/src/iosMain/kotlin/com/soywiz/korgw/DefaultGameWindowIos.kt
> Implements GameWindow.keepScreenOn on Android and iOS

- korio/src/commonMain/kotlin/com/soywiz/korio/file/Vfs.kt
- korio/src/commonMain/kotlin/com/soywiz/korio/file/VfsFile.kt
- korio/src/commonMain/kotlin/com/soywiz/korio/file/std/NodeVfs.kt
- korio/src/commonTest/kotlin/com/soywiz/korio/vfs/VfsFileTest.kt
Fixes https://github.com/korlibs/korge/issues/1048
> Adds VfsFile.deleteRecursively

- korgw/src/darwinMain/kotlin/com/soywiz/korgw/DarwinGamePad.kt
- korgw/src/iosMain/kotlin/com/soywiz/korgw/DefaultGameWindowIos.kt
- korgw/src/jvmMain/kotlin/com/soywiz/korgw/osx/MacosGameController.kt
- korgw/src/macosMain/kotlin/com/soywiz/korgw/DefaultGameWindowMacos.kt
Some work on https://github.com/korlibs/korge/issues/779
> Support Gamepad on MacOS K/N

- korge/src/commonMain/kotlin/com/soywiz/korge/view/Graphics.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/ShapeView.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/View.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/ktree/KTree.kt
- korge/src/commonTest/kotlin/com/soywiz/korge/view/ViewCollisionTest.kt
- korge/src/commonTest/kotlin/com/soywiz/korge/view/ktree/KTreeTest.kt
- korge/src/commonTest/resources/restitution.ktree
Fixes https://github.com/korlibs/korge/issues/1034
> Fixes ShapeView anchoring issues

- korio/src/commonMain/kotlin/com/soywiz/korio/file/Vfs.kt
- korio/src/commonMain/kotlin/com/soywiz/korio/file/std/LogVfs.kt
- korio/src/commonTest/kotlin/com/soywiz/korio/vfs/LocalVfsTest.kt
- korio/src/jsMain/kotlin/com/soywiz/korio/runtime/node/JsRuntimeNode.kt
- korio/src/jvmAndroidMain/kotlin/com/soywiz/korio/file/std/BaseLocalVfsJvm.kt
- korio/src/nativeMain/kotlin/com/soywiz/korio/file/std/LocalVfsNative.kt
Fixes https://github.com/korlibs/korge/issues/1060
> Fail when running Vfs.exec on an unexistant folder + implement Vfs.stat on NodeJS

- build.android.gradle
Fixes https://github.com/korlibs/korge/issues/1065
> Fix bug that was adding resource assets to the Android libraries

- buildSrc/src/main/kotlin/com/soywiz/korge/gradle/targets/jvm/JvmAddOpens.kt
- korge/src/jvmMain/kotlin/com/soywiz/korge/EnsureAddOpens.kt
- korgw/src/jvmMain/kotlin/com/soywiz/korgw/awt/BaseAwtGameWindow.kt
- korgw/src/jvmMain/kotlin/com/soywiz/korgw/internal/MicroDynamic.kt
Fixes https://github.com/korlibs/korge/issues/1074
> Fixes issue with modern JVM versions on MacOS

- korio/src/commonMain/kotlin/com/soywiz/korio/lang/jsEval.kt
- korio/src/jsMain/kotlin/com/soywiz/korio/lang/jsEval.kt
- korio/src/jsTest/kotlin/com/soywiz/korio/lang/JsEvalTest.kt
- korio/src/jvmAndroidMain/kotlin/com/soywiz/korio/lang/jsEvalJvm.kt
- korio/src/nativeMain/kotlin/com/soywiz/korio/lang/jsEvalNative.kt
Improves https://github.com/korlibs/korge/discussions/1071
> Adds JSEval to have it available in the common source set

- kds/src/commonMain/kotlin/com/soywiz/kds/SparseChunkedStackedIntArray2.kt
- kds/src/commonMain/kotlin/com/soywiz/kds/StackedIntArray2.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/animation/ImageAnimationView.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/tiles/TileMap.kt
- korge/src/commonTest/kotlin/com/soywiz/korge/tiled/TiledMapTest.kt
- korge/src/commonTest/kotlin/com/soywiz/korge/view/tiles/TileMapTest.kt
Fixes https://github.com/korlibs/korge/issues/1087
> Fixes tilemap hit-testing with sparse/infinite tilemaps

- build.gradle.kts
- buildSrc/src/main/kotlin/com/soywiz/korge/gradle/targets/jvm/Jvm.kt
- korge-reload-agent/src/main/kotlin/com/soywiz/korge/reloadagent/KorgeReloadAgent.kt
- korge/src/jvmMain/kotlin/com/soywiz/korge/KorgeReload_getReloadedClass.kt
This hugely improves the reload time in some cases by just not trying to redefine clasess by default, and actually detect real changes when redefining
> Improve reload agent

- korge/src/commonMain/kotlin/com/soywiz/korge/view/ViewRenderToBitmap.kt
Fixes https://github.com/korlibs/korge/issues/486
> Support View.renderToBitmap to render the background color too

- build.android.application.gradle
- buildSrc/src/main/kotlin/com/soywiz/korge/gradle/KorgeExtension.kt
- buildSrc/src/main/kotlin/com/soywiz/korge/gradle/targets/android/Android.kt
- korge/src/androidMain/kotlin/com/soywiz/korge/android/KorgeAndroidView.kt
- korgw/src/androidMain/kotlin/com/soywiz/korgw/DefaultGameWindowAndroid.kt
- korgw/src/androidMain/kotlin/com/soywiz/korgw/KorgwActivity.kt
- korgw/src/androidMain/kotlin/com/soywiz/korgw/KorgwSurfaceView.kt
- korgw/src/commonMain/kotlin/com/soywiz/korgw/GameWindow.kt
Fixes https://github.com/korlibs/korge/issues/516
> Supports `korge { androidMsaa = 4 }` to configure antialiased multisampled rendering on Android

- korim/src/commonMain/kotlin/com/soywiz/korim/format/ImageFormat.kt
- korim/src/darwinMain/kotlin/com/soywiz/korim/format/cg/CgRenderer.kt
- korim/src/darwinMain/kotlin/com/soywiz/korim/format/cg/NSDataExt.kt
- korim/src/iosMain/kotlin/com/soywiz/korim/format/ui/UIImageExt.kt
- korim/src/iosTest/kotlin/com/soywiz/korim/format/ui/UIImageExtTest.kt
Fixes https://github.com/korlibs/korge/discussions/789
> Supports bidirectional Bitmap <-> UIImage conversion

- korge/src/androidMain/kotlin/com/soywiz/korge/android/KorgeAndroidView.kt
- add @JvmOverloads (to use custom class in xml)
- change coroutineScope to findViewTreeLifecycleOwner().lifecycleScope
> Modify KorgeAndroidView.kt

- korio/src/androidMain/kotlin/com/soywiz/korio/net/ws/WebSocketsAndroid.kt
- korio/src/commonMain/kotlin/com/soywiz/korio/net/ws/RawSocketWebSocketClient.kt
- korio/src/commonMain/kotlin/com/soywiz/korio/net/ws/WebSocketClient.kt
- korio/src/commonTest/kotlin/com/soywiz/korio/net/ws/RawSocketWebSocketClientTest.kt
- korio/src/jsMain/kotlin/com/soywiz/korio/net/ws/WebSocketsJs.kt
- korio/src/jvmMain/kotlin/com/soywiz/korio/net/ws/WebSocketsJvm.kt
- korio/src/nativeMain/kotlin/com/soywiz/korio/net/ws/WebSocketsNative.kt
> Fixes wrong wskey=null in RawSocketWebSocketClient + add test verifying wrong length for wskey

- korgw/src/commonMain/kotlin/com/soywiz/korag/gl/AGOpengl.kt
Not quite sure how to create test for that, will be happy if you hint
> Call gl.beforeDoRender in AGOpengl

- korge/src/commonTest/kotlin/com/soywiz/korge/render/RenderContextTest.kt
- korgw/src/commonMain/kotlin/com/soywiz/kgl/KmlGlProxy.kt
> Ensure RenderContext.doRender & AGOpengl is calling ag.beforeDoRender

- korio/src/commonMain/kotlin/com/soywiz/korio/serialization/xml/Xml.kt
- korio/src/commonMain/kotlin/com/soywiz/korio/stream/SyncStream.kt
- korio/src/commonMain/kotlin/com/soywiz/korio/util/StrReader.kt
WIP on https://github.com/korlibs/korge/issues/1167
> Prepare StrReader to be extensible and support streams

- korio/src/commonMain/kotlin/com/soywiz/korio/serialization/xml/Xml.kt
- korio/src/commonMain/kotlin/com/soywiz/korio/stream/CharReader.kt
- korio/src/commonMain/kotlin/com/soywiz/korio/util/StrReader.kt
- korio/src/commonTest/kotlin/com/soywiz/korio/serialization/xml/XmlTest.kt
Supports https://github.com/korlibs/korge/discussions/1172 use-case
@multiport
> Supports XML streaming

- korge/src/commonMain/kotlin/com/soywiz/korge/scene/SceneContainer.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/scene/Transition.kt
- korge/src/commonTest/kotlin/com/soywiz/korge/scene/SceneContainerTest.kt
Fixes https://github.com/korlibs/korge/issues/1157
> Fixes & tests scene transitions parameters

- korgw/src/commonMain/kotlin/com/soywiz/korev/Input.kt
- korgw/src/mingwMain/kotlin/com/soywiz/korgw/KeyMapping.kt
Fixes https://github.com/korlibs/korge/issues/1168
> Fixes control, alt, shift not working on K/N win32

- korge/src/jvmMain/kotlin/com/soywiz/korge/testing/KorgeScreenshotValidator.kt
For example macos/windows might have slightly different vector renderings
@Kietyo
> Support slight differences between platforms when comparing goldens

- korge/src/commonMain/kotlin/com/soywiz/korge/input/GamepadEvents.kt
Thanks to "MasterOfNone" for the suggestion
> Updating deprecated text to link to other function

- korgw/src/commonMain/kotlin/com/soywiz/kgl/KmlGlProxy.kt
- korgw/src/commonMain/kotlin/com/soywiz/korag/gl/AGOpengl.kt
- korgw/src/commonMain/kotlin/com/soywiz/korag/gl/GLObjects.kt
- korgw/src/jvmTest/kotlin/com/soywiz/korgw/AGOpenglTest.kt
Fixes https://github.com/korlibs/korge/issues/1209
> Fixes context lost and adds tests for it

- korio/src/commonMain/kotlin/com/soywiz/korio/file/VfsFile.kt
- korio/src/commonTest/kotlin/com/soywiz/korio/vfs/CopyToTreeTest.kt
- korio/src/commonTest/kotlin/com/soywiz/korio/vfs/VfsFileTest.kt
- korio/src/commonTest/kotlin/com/soywiz/korio/vfs/ZipVfsTest.kt
Fixes https://github.com/korlibs/korge/issues/920
> Unifies copyToTree

- buildSrc/src/main/kotlin/com/soywiz/korlibs/root/RootKorlibsPlugin.kt
Fixes https://github.com/korlibs/korge/issues/1338
> Fix publishing korge-benchmark locally

- korge-sandbox/src/commonMain/kotlin/Main.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/input/GamepadEvents.kt
- korgw/src/commonMain/kotlin/com/soywiz/korev/Input.kt
- korgw/src/commonMain/kotlin/com/soywiz/korev/gamepad/XInput.kt
- korgw/src/jvmMain/kotlin/com/soywiz/korgw/win32/XInput.kt
- korgw/src/mingwMain/kotlin/com/soywiz/korgw/XInput.kt
Fixes https://github.com/korlibs/korge/issues/1347
> Fixes XInput mapping

- korim/src/androidMain/kotlin/com/soywiz/korim/format/NativeImageFormatProviderAndroid.kt
- korim/src/commonTest/kotlin/com/soywiz/korim/format/NativeDecodingTest.kt
Fixes https://github.com/korlibs/korge/issues/1359
> Make Android loaded bitmaps mutable to match the behaviour on the rest of the targets

- korge-sandbox/src/commonMain/kotlin/Main.kt
- korim/src/androidMain/kotlin/com/soywiz/korim/format/NativeImageFormatProviderAndroid.kt
- korim/src/commonMain/kotlin/com/soywiz/korim/bitmap/Bitmap.kt
- korim/src/commonMain/kotlin/com/soywiz/korim/paint/Filler.kt
- korim/src/commonMain/kotlin/com/soywiz/korim/paint/Paint.kt
- korim/src/commonMain/kotlin/com/soywiz/korim/vector/Bitmap32Context2d.kt
- korim/src/commonMain/kotlin/com/soywiz/korim/vector/Context2d.kt
- korim/src/commonMain/kotlin/com/soywiz/korim/vector/renderer/Renderer.kt
- korim/src/commonTest/kotlin/com/soywiz/korim/bitmap/Context2DCommonTest.kt
- korim/src/darwinMain/kotlin/com/soywiz/korim/format/cg/CgRenderer.kt
- korim/src/jsMain/kotlin/com/soywiz/korim/format/NativeImageFormatProviderJs.kt
- korim/src/jvmMain/kotlin/com/soywiz/korim/awt/AwtNativeImage.kt
- korim/src/jvmMain/kotlin/com/soywiz/korim/format/NativeImageFormatProviderJvm.kt
- korim/src/jvmTest/kotlin/com/soywiz/korim/vector/Context2dTest.kt
- korim/src/mingwMain/kotlin/com/soywiz/korim/format/GdiNativeImage.kt
- korma/src/commonMain/kotlin/com/soywiz/korma/geom/Matrix.kt
Extra gradients are now supported by rendering incompatible gradients into bitmaps and using bitmap pattern fills
> Improve vector support: better AWT bitmap cycle methods & fix sweep on CG & GDI+ & fix radial on GDI+

- buildSrc/src/main/kotlin/com/soywiz/korge/gradle/KorgeProcessResources.kt
- buildSrc/src/main/kotlin/com/soywiz/korlibs/root/RootKorlibsPlugin.kt
- korge/src/jvmMain/kotlin/com/soywiz/korge/resources/ResourceProcessorRunner.kt
https://github.com/korlibs/korge/issues/1360
Also fixes any other issues I found while trying to fix it.
> Fix task dependency issue #1360

- buildSrc/src/main/kotlin/com/soywiz/korge/gradle/targets/jvm/Jvm.kt
- korge-reload-agent/src/main/kotlin/com/soywiz/korge/reloadagent/KorgeReloadAgent.kt
Fixes https://github.com/korlibs/korge/issues/964
> Fixes ReloadAgent, display command output errors, and retry on exit after a few seconds

- kds/src/commonMain/kotlin/com/soywiz/kds/FastMap.kt
- kmem/src/commonMain/kotlin/com/soywiz/kmem/Buffer.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/render/BatchBuilder2D.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/render/LineRenderBatcher.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/render/RenderContext.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/render/RenderContext2D.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/render/RenderContext2DExt.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/debug/DebugVertexView.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/fast/FSprites.kt
- korge/src/commonMain/kotlin/com/soywiz/korge/view/vector/GpuShapeViewCommands.kt
- korgw/src/commonMain/kotlin/com/soywiz/korag/AGObjects.kt
- korgw/src/commonMain/kotlin/com/soywiz/korag/AGProgramWithUniform.kt
- korgw/src/commonMain/kotlin/com/soywiz/korag/AGValue.kt
- korgw/src/commonMain/kotlin/com/soywiz/korag/DefaultShaders.kt
- korgw/src/commonMain/kotlin/com/soywiz/korag/gl/AGOpengl.kt
- korgw/src/commonMain/kotlin/com/soywiz/korag/shader/shaders.kt
- korgw/src/commonTest/kotlin/com/soywiz/korag/AGUniformBlockTest.kt
- korgw/src/commonTest/kotlin/com/soywiz/korgw/AGUniformsTest.kt
- korgw/src/iosMacosMain/kotlin/com/soywiz/metal/AGMetal.kt
- korma/src/commonMain/kotlin/com/soywiz/korma/geom/Matrix4.kt
The OpenGL backend still doesn't upload those block buffers directly when the functionality is available
> Initial prototype of Uniform Block Buffers (already used in Proj/View matrix & material UI)

- korge-gradle-plugin/build.gradle
Likely fixes https://github.com/korlibs/korge/issues/1469
> Fixes gradle plugin id

- .github/workflows/TEST.yml
- buildSrc/src/main/kotlin/korlibs/root/RootKorlibsPlugin.kt
Since it was causing warnings related to resolving configuratons at configuration time
> Enable kover only when required

- buildSrc/src/main/kotlin/korlibs/korge/gradle/KorgeExtension.kt
- buildSrc/src/main/kotlin/korlibs/korge/gradle/Repos.kt
- buildSrc/src/main/kotlin/korlibs/korge/gradle/targets/ProjectType.kt
- buildSrc/src/main/kotlin/korlibs/korge/gradle/targets/all/All.kt
- buildSrc/src/main/kotlin/korlibs/korge/gradle/targets/android/Android.kt
- buildSrc/src/main/kotlin/korlibs/korge/gradle/targets/android/AndroidConfig.kt
- buildSrc/src/main/kotlin/korlibs/korge/gradle/targets/android/AndroidDirect.kt
- buildSrc/src/main/kotlin/korlibs/korge/gradle/targets/android/AndroidMainActivityKt.kt
- buildSrc/src/main/kotlin/korlibs/korge/gradle/targets/android/AndroidManifestXml.kt
- buildSrc/src/main/kotlin/korlibs/korge/gradle/targets/android/AndroidRun.kt
- buildSrc/src/main/kotlin/korlibs/korge/gradle/targets/android/AndroidSdk.kt
- buildSrc/src/main/kotlin/korlibs/korge/gradle/util/GradleExt.kt
- buildSrc/src/main/kotlin/korlibs/root/RootKorlibsPlugin.kt
- kmem/src/androidMain/kotlin/korlibs/memory/internal/currentAndroid.kt
- korge-gradle-plugin/build.gradle
- korge-gradle-plugin/src/test/kotlin/korlibs/korge/gradle/AndroidTest.kt
- korge-sandbox/.gitignore
Fixes https://github.com/korlibs/korge/issues/1452
> Fixes and refactor android

- korge-sandbox/src/commonMain/kotlin/Main.kt
- korge/src/commonMain/kotlin/korlibs/korge/view/CachedContainer.kt
- korgw/src/commonMain/kotlin/korlibs/graphics/DefaultShaders.kt
- korgw/src/commonMain/kotlin/korlibs/graphics/gl/AGOpengl.kt
- korgw/src/commonMain/kotlin/korlibs/graphics/shader/gl/GLVariant.kt
- korgw/src/commonMain/kotlin/korlibs/kgl/KmlGlProxy.kt
- korgw/src/iosMain/kotlin/korlibs/render/DefaultGameWindowIos.kt
Fixes https://github.com/korlibs/korge/issues/1526
> Fixes iOS rendering issue

- buildSrc/src/main/kotlin/korlibs/modules/Signing.kt
to happen only once. Replacing useInMemoryPgpKeys with a cached instance.
After profiling, this was something super slow that caused publishing all the artifacts to be delayed several minutes:
* `org.gradle.plugins.signing.signatory.pgp.PgpSignatory.createPrivateKey`
But in the end the key and the password was the same for all the artifacts, so makes sense to decode the PGP key just once and reuse it.
> Caches the PGP signatory decoding, that was performed for each artifact,

- korge/src/commonMain/kotlin/korlibs/korge/view/View.kt
Circumvents issue regarding to boxing of value classes reported here: https://youtrack.jetbrains.com/issue/KT-57860
> Optimize View.localMatrix in K/N

- korma/src/commonMain/kotlin/korlibs/math/geom/Vector2.kt
- korma/src/commonTest/kotlin/korlibs/math/geom/Vector2Test.kt
Fixes https://discord.com/channels/728582275884908604/801658049244430377/1097673814759985154
> Fixes Vector2/Point.isCollinear for fully horizontal points and repeated points

- buildSrc/src/main/kotlin/korlibs/korge/gradle/KorgeExtension.kt
- buildSrc/src/main/kotlin/korlibs/korge/gradle/targets/android/Android.kt
- buildSrc/src/main/kotlin/korlibs/korge/gradle/targets/android/AndroidMainActivityKt.kt
- buildSrc/src/main/kotlin/korlibs/korge/gradle/targets/android/AndroidManifestXml.kt
- korge/src/commonMain/kotlin/korlibs/korge/Korge.kt
- korgw/src/androidMain/kotlin/korlibs/render/KorgwActivity.kt
- korgw/src/commonMain/kotlin/korlibs/render/GameWindow.kt
Fixes https://discord.com/channels/728582275884908604/801658049244430377/1097630054281908284
> Supports android display cutout

- korau/src/commonMain/kotlin/korlibs/audio/sound/AudioData.kt
- korau/src/commonTest/kotlin/korlibs.audio.sound/AudioDataTest.kt
so infinite playback on sounds can work properly
Fixes https://github.com/korlibs/korge/issues/1559
> Fixes AudioDataStream to be able to seek and to restart

- README.md
> fix Starter kits link error for readme

- .github/workflows/TEST.yml
- buildSrc/src/main/kotlin/korlibs/korge/gradle/targets/js/Esbuild.kt
Tries to verify that https://github.com/korlibs/korge/issues/1610 fails and ensure it is fixed later
> Check browserReleaseEsbuild on all platforms

- korgw/src/androidMain/kotlin/korlibs/render/KorgwActivity.kt
- korio/src/androidMain/kotlin/korlibs/io/android/KorioAndroidContext.kt
- korio/src/androidMain/kotlin/korlibs/io/async/AsyncExtAndroid.kt
- korio/src/androidMain/kotlin/korlibs/io/file/std/VfsAndroid.kt
- korio/src/commonMain/kotlin/korlibs/io/file/Vfs.kt
- korio/src/commonTest/kotlin/korlibs/io/vfs/LocalVfsTest.kt
- korio/src/jsMain/kotlin/korlibs/io/runtime/node/JsRuntimeNode.kt
- korio/src/mingwMain/kotlin/korlibs/io/file/std/LocalVfsNativeMingw.kt
- korio/src/nativeMain/kotlin/korlibs/io/file/std/LocalVfsNative.kt
Fixes https://github.com/korlibs/korge/issues/1733
> Fixes korio: "Flow invariant is violated" in Vfs.listFlow()

- korge/src/commonMain/kotlin/korlibs/korge/input/Input.kt
- korge/src/commonMain/kotlin/korlibs/korge/input/KeysEvents.kt
- korge/src/commonMain/kotlin/korlibs/korge/view/Views.kt
- korge/src/commonTest/kotlin/korlibs/korge/input/KeysEventsTest.kt
So you can have a single block and a single Closeable to handle some kind of events
> Support providing a set of possible keys for key events

- korau/src/commonMain/kotlin/korlibs/audio/sound/PlatformAudioOutput.kt
- korau/src/commonMain/kotlin/korlibs/audio/sound/backends/ALSA.kt
- korau/src/jvmMain/kotlin/korlibs/audio/sound/backends/ALSAImpl.kt
- korau/src/nativeMain/kotlin/korlibs/audio/sound/backends/ALSAImpl.kt
> Simplify and fix ALSA implementation using DequeBasedPlatformAudioOutput

- docs/korma/binpacker/index.md
in KorMA > BinPacker, from "thighly packed" to "tightly packed"
> fix typo "thighly" -> "tightly"

- korge-benchmarks/build.gradle.kts
- korge-gradle-plugin/build.gradle.kts
- korge-reload-agent/build.gradle.kts
Retake on https://github.com/korlibs/korge/pull/1828
> Convert some build.gradle into build.gradle.kts

- korge-foundation/src/commonMain/kotlin/korlibs/math/geom/Size.kt
- korge-foundation/src/commonMain/kotlin/korlibs/math/geom/_MathGeomMutable.kt
- korge/src/commonMain/kotlin/korlibs/korge/render/RenderContext2DExt.kt
- korge/src/commonMain/kotlin/korlibs/korge/ui/UIProgressBar.kt
- korge/src/commonMain/kotlin/korlibs/korge/ui/UIScrollableArea.kt
- korge/src/commonMain/kotlin/korlibs/korge/ui/UIVerticalList.kt
Superseeds https://github.com/korlibs/korge/pull/1821
> Some number constructors

- buildSrc/src/main/kotlin/korlibs/korge/gradle/KorgeGradlePlugin.kt
- buildSrc/src/main/kotlin/korlibs/korge/gradle/targets/SourceSets.kt
- buildSrc/src/main/kotlin/korlibs/korge/gradle/targets/apple/InfoPlistBuilder.kt
- buildSrc/src/main/kotlin/korlibs/korge/gradle/targets/desktop/DesktopJreBundler.kt
- buildSrc/src/main/kotlin/korlibs/korge/gradle/targets/ios/Ios.kt
- buildSrc/src/main/kotlin/korlibs/korge/gradle/targets/jvm/Jvm.kt
- buildSrc/src/main/kotlin/korlibs/root/RootKorlibsPlugin.kt
- korge-gradle-plugin/src/main/kotlin/com/soywiz/kproject/KProjectPlugin.kt
To explore to reduce .app final size:
* https://incenp.org/notes/2023/universal-java-app-on-macos.html
> Supports packing macos app with a bundled Universal (ARM+x64) JRE

- korge-foundation/src/common/korlibs/datastructure/_Datastructure_event.kt
- korge-foundation/test/common/korlibs/datastructure/event/SyncEventLoopTest.kt
Supporting timers and normal tasks, precise timing & waking from sleep
> Added SyncEventLoop

- korge-core/src/common/korlibs/io/lang/Closeable.kt
- korge-foundation/src/common/korlibs/datastructure/_Datastructure_event.kt
- korge-foundation/src/common/korlibs/datastructure/_Datastructure_thread.kt
- korge-foundation/src/common/korlibs/datastructure/_Delegates.kt
- korge-foundation/src/common/korlibs/time/Frequency.kt
- korge-foundation/src/darwin/korlibs/datastructure/thread/NativeThread.kt
- korge-foundation/src/js/korlibs/datastructure/thread/NativeThread.kt
- korge-foundation/src/jvmAndroid/korlibs/datastructure/thread/NativeThread.kt
- korge/src/common/korlibs/korge/Korge.kt
- korge/src/common/korlibs/korge/view/Views.kt
- korge/src/common/korlibs/render/DialogInterface.kt
- korge/src/common/korlibs/render/GameWindow.kt
- korge/src/common/korlibs/render/SyncEventLoopCoroutineDispatcher.kt
- korge/src/jvm/korlibs/render/DefaultGameWindowJvm.kt
- korge/src/jvm/korlibs/render/awt/AwtAGOpenglCanvas.kt
- korge/src/jvm/korlibs/render/awt/AwtFrameTools.kt
- korge/src/jvm/korlibs/render/awt/AwtGameWindow.kt
- korge/src/jvm/korlibs/render/awt/BaseAwtGameWindow.kt
- korge/src/jvm/korlibs/render/awt/NewAwtGameWindow.kt
- korge/src/jvm/korlibs/render/osx/metal/MTL.kt
- korge/src/jvm/korlibs/render/platform/AwtTools.kt
- korge/src/jvm/korlibs/render/platform/BaseOpenglContext.kt
- korge/test/jvm/korlibs/render/awt/AwtGameWindowTest.kt
This will simplify and improve GameWindow to update and render separately in separate threads.
Updates and events will happen separately to the rendering and without waiting for vsync fixing long-standing issues.
Also the GameWindow was really polluted and was confusing due to patches added to many targets.
> Prepare new GameWindow

- korge/src/common/korlibs/korge/Korge.kt
- korge/src/common/korlibs/render/GameWindow.kt
- korge/src/jvm/korlibs/render/awt/AwtGameWindow.kt
Backport https://github.com/korlibs/korge/pull/1726 from @cmhulbert
> Backport supporting undecorated AWT window

- korge/src/common/korlibs/korge/audio/AudioChannel.kt
- korge/test/common/korlibs/korge/audio/AudioChannelTest.kt
As discussed here: https://github.com/korlibs/korge/discussions/2017
> Adds AudioChannel to KorGE

- korge-core/src/common/korlibs/ffi/ExecutableResolver.kt
- korge-core/src/common/korlibs/ffi/LDLibraries.kt
- korge-core/src/common/korlibs/ffi/LibraryResolver.kt
- korge-core/src/common/korlibs/io/file/Vfs.kt
- korge-core/src/common/korlibs/io/file/VfsFile.kt
- korge-core/src/common/korlibs/io/file/sync/SyncIO.kt
- korge-core/src/darwin/korlibs/io/file/std/LocalVfsNative.kt
- korge-core/src/darwin/korlibs/io/file/std/StandardBasePathsDarwin.kt
- korge-core/src/darwin/korlibs/io/file/sync/SyncIONative.kt
- korge-core/src/js/korlibs/io/file/sync/platformSyncIO.kt
- korge-core/src/jvm/korlibs/ffi/FFILib.jvm.kt
- korge-core/src/jvm/korlibs/io/file/std/LocalVfsJvm.kt
- korge-core/src/jvmAndroid/korlibs/io/file/std/AsynchronousFileChannelVfs.kt
- korge-core/src/jvmAndroid/korlibs/io/file/std/BaseLocalVfsJvm.kt
- korge-core/src/jvmAndroid/korlibs/io/file/sync/platformSyncIO.kt
- korge-core/src/jvmAndroid/korlibs/io/util/ExecuteIo.kt
- korge-core/src/jvmAndroid/korlibs/io/util/JvmFsCaseSensitive.kt
- korge-core/test/common/korlibs/io/file/std/CaseSensitiveTest.kt
Fixes https://github.com/korlibs/korge/issues/599
Fixes https://github.com/korlibs/korge/discussions/2037#discussioncomment-7667196
> Make local and resources vfs case-sensitive on JVM Windows to avoid porting issues

- korge-core/src@jvmAndroid/korlibs/io/hash/HashJvmExt.kt
- korge-core/test@jvm/korlibs/io/hash/HashJvmExtTest.kt
- korge-foundation/src/korlibs/crypto/Hasher.kt
Some work on https://github.com/korlibs/korge/issues/1710
> Adds JVM InputStream.hash

- .gitattributes
Based on https://github.com/hiperbou/doom-ktor/blob/master/.gitattributes
> Try to void repo being detected as Webassembly instead of Kotlin

- korge-core/src@darwin/korlibs/io/file/std/LocalVfsNative.kt
- korge-core/src@darwin/korlibs/io/posix/PosixExtExpect.kt
Fixes https://github.com/korlibs/korge/discussions/1811
> Implements time information in Vfs.stat on iOS

- .github/workflows/DEPLOY.yml
Fixes https://github.com/korlibs/korge/issues/2115
> Use a build matrix for publishing + include K/N desktop publishing

- korge/src/korlibs/korge/resources/ResourcesExt.kt
Fixes https://github.com/korlibs/korge/issues/302
> Adds resourceSound and resourceMusic

- korge-core/src/korlibs/audio/sound/Sound.kt
- korge-core/src/korlibs/audio/sound/fade/SoundChannelFade.kt
- korge-core/test@jvm/korlibs/audio/impl/jna/JnaSoundProviderSample.kt
Fixes https://github.com/korlibs/korge/issues/450
> Improve SoundChannelGroup API

- korge/src/korlibs/korge/tween/tweenbase.kt
Fixes https://github.com/korlibs/korge/issues/2183
> Fixes V2.duration conflict

- korlibs-template/src/korlibs/template/KorteDefaults.kt
- korlibs-template/test/korlibs/template/TemplateTest.kt
Fixes https://github.com/korlibs/korge/issues/2198
> Templates: Support elsif in addition to elseif

- buildSrc/src/main/kotlin/korlibs/korge/gradle/KorgeExtension.kt
- buildSrc/src/main/kotlin/korlibs/korge/gradle/targets/android/AndroidConfig.kt
- buildSrc/src/main/kotlin/korlibs/korge/gradle/targets/android/AndroidManifestXml.kt
Fixes https://github.com/korlibs/korge/issues/2241
> Support extract ManifestXml application attrributes

- korge/src/korlibs/korge/text/TextEditController.kt
Fixes https://github.com/korlibs/korge/issues/2155
> Fixes ctrl+something typing on windows and avoid clipboard errors to fail cutting
