korlibs/korge

README.md
Corrects the formatting of the README.
=> Add a missing backtick.

korge/src/androidMain/kotlin/com/soywiz/korge/service/vibration/NativeVibration.kt, korge/src/commonMain/kotlin/com/soywiz/korge/service/vibration/NativeVibration.kt, korge/src/jsMain/kotlin/com/soywiz/korge/service/vibration/NativeVibration.kt, korge/src/jvmMain/kotlin/com/soywiz/korge/service/vibration/NativeVibration.kt, korge/src/nativeCommonMain/kotlin/com/soywiz/korge/service/vibration/NativeVibration.kt
Without JDoc the vibration usage is hard to understand and behaves different on JS and Android. And it always uses the maxium vibration amplitude.
For example to vibrate 200ms on Android, you had to write:
``` kotlin
vibrate(longArrayOf(0, 42))
```
**Changes**
* Add `vibrate(time: TimeSpan, amplitude: UInt)`
* Add single vibration
* Add amplitude for Android target (_amplitude intensity of the vibration [0-255])_
* Renamed `vibrate(..)` to `vibratePattern` - nessesary to resolve name clash on expect/actual matching
* Renamed pattern to timings
* Fix pattern usage:
Pattern is always a list of timings for ON and OFF sequences. But on JS it starts with ON, on Android 
with OFF. So this fix adds a empty off timing for Android.
* Add JDoc for vibration methods
It's discussible if `amplitude` …
=> Add amplitude to NativeVibration

korge/src/androidMain/kotlin/com/soywiz/korge/service/vibration/NativeVibration.kt
Now I know hot to build and test it locally. And of course it was broken.
The `toAndroidAmplitude` returned maximum 1 😣
=> Fix native vibration amplitude on Android

korge/src/commonMain/kotlin/com/soywiz/korge/bus/Bus.kt
**New:** Adds a reified version of the register method to get a nicer API.
So instead of writing:
``` kotlin
bus.register(SomeEvent::class){ someEventListener() }
```
We can provide the type in a generic way without the `::class`.
``` kotlin
bus.register<SomeEvent> { someEventListener(it) }
```
**Refactoring:** Removes the unsed `InjectedHandler`
=> Add reified typed register to Bus

korge/src/commonMain/kotlin/com/soywiz/korge/animate/Animator.kt
Add `onCancel` callback to Animator in order to run some actions when animation is cancelled.
Also wrap execution of Parallel node in try-catch block with CancellationException.
=> Add additional onCancel callback to Animator

korge/src/commonMain/kotlin/com/soywiz/korge/view/filter/ShaderFilter.kt
To allow devs to set it false when making pixel art games. Tries to fix #107
=>  Create filtering field inside ShaderFilter

korge/src/commonMain/kotlin/com/soywiz/korge/input/MouseEvents.kt
There is an uninitialized `views` exception in `MouseEvents` in special cases when `update` function is called before any events are performed (`views` is initialized only in `onMouseEvent` function). This PR fixes this.
=> Fix uninitialized exception in MouseEvents

korge/src/commonMain/kotlin/com/soywiz/korge/view/RoundRect.kt, korge/src/commonTest/kotlin/com/soywiz/korge/view/ViewsTest.kt
Add RoundRect as a separate view (like SolidRect or CIrcle), so you don't have to use `graphics { ... }` when you need a rectangle with rounded corners.
=> Add RoundRect as a separate view

korge/src/commonMain/kotlin/com/soywiz/korge/input/MouseEvents.kt, korge/src/commonMain/kotlin/com/soywiz/korge/view/Stage.kt
Fixes #240
Also makes the Stage implement ViewsScope
Please, instead of squashing, let rebase and merge this so the Stage implement ViewsScope is kept in a separate commit
=> Allows to install the mouse debug layer without any mouse event registered

gradle.properties
Fixes #213 
Since fixed happened on korgw but inline methods were somehow affected, we need to update korgw version here too
Fixed here: https://github.com/korlibs/korgw/pull/38
=> Filters caused black screens on AWT JVM on Macos and potentially Windows. Fixes #213

korge/src/commonMain/kotlin/com/soywiz/korge/Korge.kt, korge/src/commonMain/kotlin/com/soywiz/korge/ui/IconButton.kt, korge/src/commonMain/kotlin/com/soywiz/korge/ui/TextButton.kt, korge/src/commonMain/kotlin/com/soywiz/korge/ui/UIButton.kt, korge/src/commonMain/kotlin/com/soywiz/korge/ui/UICheckBox.kt, korge/src/commonMain/kotlin/com/soywiz/korge/ui/UIComboBox.kt, korge/src/commonMain/kotlin/com/soywiz/korge/ui/UIProgressBar.kt, korge/src/commonMain/kotlin/com/soywiz/korge/ui/UIScrollBar.kt, korge/src/commonMain/kotlin/com/soywiz/korge/ui/UIScrollableArea.kt, korge/src/commonMain/kotlin/com/soywiz/korge/ui/UIText.kt, korge/src/commonMain/kotlin/com/soywiz/korge/view/Camera.kt, korge/src/commonMain/kotlin/com/soywiz/korge/view/Circle.kt, korge/src/commonMain/kotlin/com/soywiz/korge/view/ClipContainer.kt, korge/src/commonMain/kotlin/com/soywiz/korge/view/Container.kt, korge/src/commonMain/kotlin/com/soywiz/korge/view/Ellipse.kt, korge/src/commonMain/kotlin/com/soywiz/korge/view/FixedSizeContainer.kt, korge/src/commonMain/kotlin/com/soywiz/korge/view/Graphics.kt, korge/src/commonMain/kotlin/com/soywiz/korge/view/Image.kt, korge/src/commonMain/kotlin/com/soywiz/korge/view/NinePatch.kt, korge/src/commonMain/kotlin/com/soywiz/korge/view/NinePatchEx.kt, korge/src/commonMain/kotlin/com/soywiz/korge/view/RoundRect.kt, korge/src/commonMain/kotlin/com/soywiz/korge/view/ScaleView.kt, korge/src/commonMain/kotlin/com/soywiz/korge/view/SolidRect.kt, korge/src/commonMain/kotlin/com/soywiz/korge/view/Sprite.kt, korge/src/commonMain/kotlin/com/soywiz/korge/view/Text.kt, korge/src/commonMain/kotlin/com/soywiz/korge/view/Text2.kt, korge/src/commonMain/kotlin/com/soywiz/korge/view/View.kt, korge/src/commonMain/kotlin/com/soywiz/korge/view/tiles/TileMap.kt
Created an annotation that now is a dummy annotation but that can be changed to an typealias for KorDslMarker so we can switch to it fast and check stuff
Fixes #262
=> Disable DSL scope limiting by removing KorDslMarker from View.

korge/src/commonMain/kotlin/com/soywiz/korge/view/SpriteAnimation.kt
SpriteAnimation's companion invoke was the only way to create a SpriteAnimation without a way to set the frametime. This just adds it in.
=> Add timePerFrame to SpriteAnimation's companion invoke

korge/src/commonMain/kotlin/com/soywiz/korge/view/ViewCollision.kt
Hello, this is my first open source PR so feel free to tell me if I'm doing something wrong here.
I use Unity a lot and I thought Korge lacked a collision exiting function. I think this is really useful to avoid using hitTest inside an updater to do it manually, and you cannot use shapes with this method.
Example case : detecting when a player is falling down a platform
I hope you'll consider it :blush:
=> Add onCollisionExit extension functions to View

korge/src/commonMain/kotlin/com/soywiz/korge3d/animation/Animator3D.kt, korge/src/jvmTest/kotlin/com/soywiz/korge/korge3d/main.kt
Currently for 3D animations it's only possible to play a collection
of them in a loop, with regular speed. The goal of this change is to
prepare the API for more fine-grained control over a single animation:
customizing playback speed, reversing playback, setting arbitrary progress
and more. That's why I recommend changing Animator3D's API to handle
a single animation instead of a collection.
I'm planning to extend the API as described above in the subsequent commits,
and would like this breaking change to go as a separate PR for better
visibility. Further changes will be backward-compatible.
This is a breaking API change, but given that KorGE 3D is still
experimental, I presume it's fine to just mention it in the release
notes. See a change in …
=> [#307] Make Animator3D handle single Animation

korge/src/commonMain/kotlin/com/soywiz/korge/ui/UIContainerLayouts.kt
Fix of a mistake in setting width for **horizontal** stack
This bug makes `UiHorizontalStack` absolutely broken and useless
=> Fix UiHorizontalStack width calculation

README.md
When newcomers find the korge repo with all of the stars and issues, it can be off-putting to think that there have been no changes or releases for almost a year. Updating the readme to mention active development in korge-next can help alleviate this issue.
=> Update README to mention korge-next

korge-reload-agent/src/main/kotlin/com/soywiz/korge/reloadagent/KorgeReloadAgent.kt, korge-sandbox/src/commonMain/kotlin/samples/MainSWF.kt, korge/src/androidMain/kotlin/com/soywiz/korge/KorgeReload_getReloadedClass.kt, korge/src/commonMain/kotlin/com/soywiz/korge/KorgeReload.kt, korge/src/commonMain/kotlin/com/soywiz/korge/scene/SceneContainer.kt, korge/src/jsMain/kotlin/com/soywiz/korge/KorgeReload_getReloadedClass.kt, korge/src/jvmMain/kotlin/com/soywiz/korge/KorgeReload_getReloadedClass.kt, korge/src/nativeMain/kotlin/com/soywiz/korge/KorgeReloadNative.kt, korinject/src/commonMain/kotlin/com/soywiz/korinject/AsyncInjector.kt, korinject/src/jvmAndroidMain/kotlin/com/soywiz/korinject/AsyncInjectorJvmExt.kt
This overcomes the limitations of hot reloading from the initial implementation.
Now we can add, remove and rename methods and properties and reloading should still work properly.
More work on https://github.com/korlibs/korge/issues/477
=> 🔥 Support hot reloading with method additions/removals

korgw/src/commonMain/kotlin/com/soywiz/korgw/GameWindow.kt
Defaults to 16.milliseconds, that allows to run games at 60fps, but can be configured to more time to avoid delaying events for later execution in future frames.
Multithreaded rendering will improve this.
=> Allow to configure time available per frame to execute tasks

korma/src/commonMain/kotlin/com/soywiz/korma/geom/Matrix3D.kt
https://docs.microsoft.com/en-us/windows/win32/direct3d9/d3dxmatrixlookatlh?redirectedfrom=MSDN#remarks
zaxis = normal(At - Eye)
xaxis = normal(cross(Up, zaxis))
yaxis = cross(zaxis, xaxis)
xaxis.x           yaxis.x           zaxis.x          0
xaxis.y           yaxis.y           zaxis.y          0
xaxis.z           yaxis.z           zaxis.z          0
-dot(xaxis, eye)  -dot(yaxis, eye)  -dot(zaxis, eye)  1
=> fix Matrix3D.setToLookAt bug

korge/build.gradle, korge/src/androidMain/kotlin/com/soywiz/korge/KorgeReload_getReloadedClass.kt, korge/src/commonMain/kotlin/com/soywiz/korge/KorgeReload.kt, korge/src/commonMain/kotlin/com/soywiz/korge/debug/UiEditProperties.kt, korge/src/commonMain/kotlin/com/soywiz/korge/scene/SceneContainer.kt, korge/src/commonMain/kotlin/com/soywiz/korge/view/ViewDebugExtra.kt, korge/src/commonTest/kotlin/com/soywiz/korge/view/ViewDebugTest.kt, korge/src/jsMain/kotlin/com/soywiz/korge/KorgeReload_getReloadedClass.kt, korge/src/jvmMain/kotlin/com/soywiz/korge/KorgeExtJvm.kt, korge/src/jvmMain/kotlin/com/soywiz/korge/KorgeReload_getReloadedClass.kt, korge/src/jvmMain/kotlin/com/soywiz/korge/awt/ViewsDebugger.kt, korge/src/nativeMain/kotlin/com/soywiz/korge/KorgeReloadNative.kt
```kotlin
class MyScene : Scene() {
@KeepOnReload var textSize = 100.0 // If this value is modified at runtime, the new value will be persisted if we hotreload the scene. Effectively making modifying this value when compiling a no-op until the app is closed and reopened. You can also remove the annotation to modify again the value by code.
@KeepOnReload var positionX by Delegates.observable(50.0) { _, _, _ -> reload() } // It even works with delegates! So we can register it later.
// Also when a scene is reloaded the SContainer view will be highlighted, so the debug components will appear
fun SContainer.sceneMain() {
// Now we can add a debug component and use the views debugger to manually adjust properties that will be persisted later
extraBuildDebugComponent = { views, view, container …
```
=> Support keeping some scene properties while hot reloading

korge-sandbox/src/commonMain/kotlin/samples/MainVectorNinePatch.kt, korge/src/commonMain/kotlin/com/soywiz/korge/view/NinePatchShapeView.kt, korim/src/commonMain/kotlin/com/soywiz/korim/vector/NinePatchShape.kt, korim/src/commonMain/kotlin/com/soywiz/korim/vector/NinePatchVector.kt, korim/src/commonMain/kotlin/com/soywiz/korim/vector/Shape.kt, korma/src/commonMain/kotlin/com/soywiz/korma/geom/Size.kt
https://user-images.githubusercontent.com/99644907/190603955-7a14c874-da9a-4ea6-89e7-ba9cba5b41b6.mov
```kotlin
class MainVectorNinePatch : Scene() {
val mouseX get() = sceneView.localMouseX(views)
val mouseY get() = sceneView.localMouseY(views)
override suspend fun SContainer.sceneMain() {
val view = ninePatchShapeView(buildShape {
fill(Colors.RED) {
roundRect(0, 0, 300, 300, 75, 75)
rect(0, 225, 75, 75)
}
fill(Colors.WHITE) {
roundRect(10, 10, 300 - 20, 300 - 20, 45, 45)
}
}.ninePatch(
NinePatchSlices(77.0 until (300.0 - 77.0)),
NinePatchSlices(77.0 until (300.0 - 77.0)),
))
addUpdater {
view.setSize(mouseX, mouseY)
}
}
}
```
=> Support scalable vector shapes with 9-patch, NinePatchShape and NinePatchShapeView

korge-sandbox/src/commonMain/kotlin/samples/MainVectorNinePatch.kt, korge-sandbox/src/commonMain/resources/chat-bubble.svg, korim/src/commonMain/kotlin/com/soywiz/korim/util/NinePatchSlices.kt, korim/src/commonMain/kotlin/com/soywiz/korim/util/NinePatchSlices2D.kt, korim/src/commonMain/kotlin/com/soywiz/korim/vector/NinePatchShape.kt, korim/src/commonMain/kotlin/com/soywiz/korim/vector/Shape.kt, korim/src/commonTest/kotlin/com/soywiz/korim/vector/NinePatchShapeTest.kt, korim/src/commonTest/resources/chat-bubble.svg, korma/src/commonMain/kotlin/com/soywiz/korma/geom/range/OpenRange.kt
https://user-images.githubusercontent.com/99644907/190616668-b55be7cb-39cc-4ba7-b8da-682d7ad76131.mov
So the idea here is to create a SVG file that has some strokes of a specific color (by default fuchsia #ff00ff) along the rest of the vectors. This functionality allows to read that SVG, strip those guide lines and use them as cut points for the generic 9-patch slices.
```kotlin
class MainVectorNinePatch : Scene() {
val mouseX get() = sceneView.localMouseX(views)
val mouseY get() = sceneView.localMouseY(views)
override suspend fun SContainer.sceneMain() {
val view = ninePatchShapeView(
resourcesVfs["chat-bubble.svg"]
.readSVG()
.toShape()
.toNinePatchFromGuides(guideColor = Colors.FUCHSIA)
)
addUpdater {
view.setSize(mouseX, mouseY)
}
}
}
```
Those guides can be created with any vector …
=> Support loading SVG files with guides that act as 9-patches

korge-sandbox/src/commonMain/kotlin/samples/MainVectorNinePatch.kt, korim/src/commonMain/kotlin/com/soywiz/korim/vector/Shape.kt
This can help to get bigger versions of an SVG, then use that as 9-patch. So for example the maximum corners are bigger.
=> Support transforming shapes. Added Shape.transformedShape, Shape.scaledShape, Shape.translatedShape

korim/src/commonMain/kotlin/com/soywiz/korim/util/NinePatchSlices2D.kt, korim/src/commonMain/kotlin/com/soywiz/korim/vector/NinePatchShape.kt, korim/src/commonMain/kotlin/com/soywiz/korim/vector/NinePatchVector.kt, korma/src/commonMain/kotlin/com/soywiz/korma/geom/PointArrayList.kt
This would help for example to create extra guides for padding/margin content inside the nine patch, for example in a chat bubble
=> Added NinePatch*.getScaledPointAt methods to get what the point would be in a rescaled surface

korim/src/commonMain/kotlin/com/soywiz/korim/font/TtfFont.kt, korim/src/jvmTest/kotlin/com/soywiz/korim/font/ttf/TtfFontTest.kt
Fixes https://github.com/korlibs/korge/issues/954
=> Fixes ¿¡ symbols not displayed properly with the default font

korge-sandbox/src/commonMain/kotlin/samples/MainInput.kt, korge/src/commonMain/kotlin/com/soywiz/korge/input/GamepadEvents.kt, korgw/src/commonMain/kotlin/com/soywiz/korev/Input.kt, korgw/src/jvmMain/kotlin/com/soywiz/korgw/osx/Cocoa.kt, korgw/src/jvmMain/kotlin/com/soywiz/korgw/osx/MacosGameController.kt, korma/src/commonMain/kotlin/com/soywiz/korma/geom/Point.kt, korma/src/commonMain/kotlin/com/soywiz/korma/internal/Internal.kt, korma/src/commonMain/kotlin/com/soywiz/korma/math/Math.kt
Some work on https://github.com/korlibs/korge/issues/779
=> Add gamepad support to MacOS on the JVM

kds/src/commonMain/kotlin/com/soywiz/kds/diff/Diff.kt, korge-sandbox/src/commonMain/kotlin/Main.kt, korgw/src/commonMain/kotlin/com/soywiz/korev/Input.kt, korgw/src/commonMain/kotlin/com/soywiz/korgw/x11/X11Joy.kt, korgw/src/linuxMain/kotlin/com/soywiz/korgw/X11GameWindow.kt, korio/src/commonMain/kotlin/com/soywiz/korio/file/sync/SyncIO.kt, korio/src/jsMain/kotlin/com/soywiz/korio/file/sync/platformSyncIO.kt, korio/src/jvmAndroidMain/kotlin/com/soywiz/korio/file/sync/platformSyncIO.kt, korio/src/nativeMain/kotlin/com/soywiz/korio/file/sync/SyncIONative.kt
Some work on https://github.com/korlibs/korge/issues/779
=> Improved linux Gamepad support on JVM & support for Gamepad on K/N & Add SyncIO

korge/src/commonTest/kotlin/com/soywiz/korge/atlas/AtlasInfoTest.kt, korim/src/commonMain/kotlin/com/soywiz/korim/bitmap/BitmapSlice.kt
`BmpSlice.extractWithBase()` returns Bitmaps with wrong content, if BmpSlice is rotated
=> Fix bug in BmpSlice.extractWithBase()

kds/src/commonMain/kotlin/com/soywiz/kds/SparseChunkedStackedIntArray2.kt, kds/src/commonMain/kotlin/com/soywiz/kds/StackedIntArray2.kt, kds/src/commonMain/kotlin/com/soywiz/kds/ds/BVH.kt, kds/src/commonMain/kotlin/com/soywiz/kds/ds/CSBVH.kt, kds/src/commonTest/kotlin/com/soywiz/kds/SparseChunkedStackedIntArray2Test.kt, kds/src/commonTest/kotlin/com/soywiz/kds/StackedIntArray2Test.kt, korge/src/commonMain/kotlin/com/soywiz/korge/view/tiles/TileMap.kt, korim/src/commonMain/kotlin/com/soywiz/korim/tiles/tiled/TiledMap.kt, korim/src/commonMain/kotlin/com/soywiz/korim/tiles/tiled/TiledMapReader.kt, korim/src/commonMain/kotlin/com/soywiz/korim/tiles/tiled/TiledMapWriter.kt, korma/src/commonMain/kotlin/com/soywiz/korma/geom/ds/BVH2D.kt, korma/src/commonMain/kotlin/com/soywiz/korma/geom/ds/BVH3D.kt
Fixes https://github.com/korlibs/korge/issues/1077
=> Supports sparse infinite tilemaps with BVH for spatial finding

kmem/src/commonMain/kotlin/com/soywiz/kmem/Fixed.kt, kmem/src/commonTest/kotlin/com/soywiz/kmem/FixedTest.kt
In some cases floating point (Double, Float) might yield imprecissions, Fixed should fix that problem while having a decent performance.
=> Prototype Fixed point arithmetic

korim/src/androidMain/kotlin/com/soywiz/korim/format/NativeImageFormatProviderAndroid.kt, korim/src/commonMain/kotlin/com/soywiz/korim/format/ImageDataContainer.kt, korim/src/commonMain/kotlin/com/soywiz/korim/format/ImageFormat.kt, korim/src/commonMain/kotlin/com/soywiz/korim/format/NativeImageFormatProvider.kt, korim/src/commonTest/kotlin/com/soywiz/korim/format/NativeEncodingTest.kt, korim/src/darwinMain/kotlin/com/soywiz/korim/format/cg/CGImageExt.kt, korim/src/darwinMain/kotlin/com/soywiz/korim/format/cg/CGNativeImageFormatProvider.kt, korim/src/darwinMobileMain/kotlin/com/soywiz/korim/format/NativeImageFormatProviderIos.kt, korim/src/darwinMobileMain/kotlin/com/soywiz/korim/format/ui/UIImageExt.kt, korim/src/jsMain/kotlin/com/soywiz/korim/format/NativeImageFormatProviderJs.kt, korim/src/jvmMain/kotlin/com/soywiz/korim/format/NativeImageFormatProviderJvm.kt, korim/src/nativeMain/kotlin/com/soywiz/korim/format/StbImageImageFormatProvider.kt
Fixes https://github.com/korlibs/korge/issues/1119
=> Support native image encoding on native image formats

korge/src/commonMain/kotlin/com/soywiz/korge/animate/Animator.kt
Use case:
if there is already animation running, and it wasn't finished (isActive), don't do anything. Otherwise re-create animation.
=> Add isActive check to animator

korgw/src/commonMain/kotlin/com/soywiz/korag/shader/shaders.kt, korgw/src/commonTest/kotlin/com/soywiz/korgw/AGUniformsTest.kt, korma/src/commonMain/kotlin/com/soywiz/korma/geom/Matrix3D.kt
Some work on https://github.com/korlibs/korge/issues/1116 & https://github.com/korlibs/korge/issues/465
For example for projection matrices, we should be able to push and pop indices in the UniformBlockBuffer, and only add new values to the buffer when the matrices change.
When doing a draw, we should reference the uniform buffers & indices in them. So we can upload the uniform buffers once, and reuse them later.
=> Add UniformBlockData & UniformBlockBuffer

korio/src/commonMain/kotlin/com/soywiz/korio/lang/Charset.kt, korio/src/commonMain/kotlin/com/soywiz/korio/stream/CharReader.kt, korio/src/commonTest/kotlin/com/soywiz/korio/lang/CharsetTest.kt, korio/src/commonTest/kotlin/com/soywiz/korio/stream/CharReaderTest.kt, korio/src/jsMain/kotlin/com/soywiz/korio/lang/CharsetJs.kt, korio/src/jsMain/kotlin/com/soywiz/korio/lang/UTF8.kt, korio/src/jvmAndroidMain/kotlin/com/soywiz/korio/lang/CharsetJvm.kt, korio/src/jvmTest/kotlin/com/soywiz/korio/lang/CharsetJvmTest.kt
https://github.com/korlibs/korge/discussions/1172
=> Adds CharReader & CharReaderFromSyncStream & allows Charset.decode to support streams

.github/workflows/TEST.yml, build.gradle.kts, buildSrc/src/main/kotlin/com/soywiz/korge/gradle/KorgeGradlePlugin.kt, buildSrc/src/main/kotlin/com/soywiz/korge/gradle/KorgeVersionsTask.kt, buildSrc/src/main/kotlin/com/soywiz/korge/gradle/util/FileExt.kt, buildSrc/src/main/kotlinGen/com/soywiz/korge/gradle/BuildVersions.kt, gradle.properties, gradle/libs.versions.toml, korge-reload-agent/build.gradle, korgw/src/macosMain/kotlin/com/soywiz/korgw/DefaultGameWindowMacos.kt, kotlin-js-store/yarn.lock
No plans to merge, but let's see if the code is still compiling
Related issue:
* https://youtrack.jetbrains.com/issue/KT-55104
=> Update to Kotlin 1.8.0

korim/src/commonMain/kotlin/com/soywiz/korim/font/LazyBitmapFont.kt, korim/src/commonTest/kotlin/com/soywiz/korim/font/LazyBitmapFontTest.kt
Fixes https://github.com/korlibs/korge/issues/1207
=> Fixes characters from being slightly displaced and spaces showing a dot in a LazyBitmapFont

buildSrc/src/main/kotlin/com/soywiz/korge/gradle/KorgeExtension.kt, buildSrc/src/main/kotlin/com/soywiz/korge/gradle/targets/native/NativeExt.kt, buildSrc/src/main/kotlin/com/soywiz/korlibs/root/RootKorlibsPlugin.kt, gradle/libs.versions.toml
Rationale of removing flags here: https://youtrack.jetbrains.com/issue/KT-56395/Kotlin-1.8.10-stdoncecallable-error-on-K-N-windows#focus=Comments-27-6835406.0-0
Kotlin 1.8.10 changelog: https://github.com/JetBrains/kotlin/releases/tag/v1.8.10
=> Bump to Kotlin 1.8.10, unify K/N configuration and disable custom freeCompilerArgs

korge/src/jvmTest/kotlin/com/soywiz/korge/render/BatchBuilderShaderTest.kt, korgw/src/commonMain/kotlin/com/soywiz/korag/gl/AGOpengl.kt, korgw/src/commonMain/kotlin/com/soywiz/korag/shader/gl/GlslGenerator.kt, korgw/src/commonMain/kotlin/com/soywiz/korag/shader/shaders.kt
If some consumers require it, they can convert the texture with another shader. This should simplify code along avoid specific driver bugs with complex shaders with external samplers
=> Remove external sampler functionality

.github/workflows/TEST.yml
Tried docker with ubuntu server, vmware with ubuntu server images, wsl2.
The same with a window machine: tried docker with nanoserver/server and vmware with windows server 2022 minimum to try to reproduce a very small environment and was not able to reproduce context errors on windows/linux/mac.
In the case of linux I was not able to reproduce this error, except when DISPLAY/xvfb was not set. So let's try to use environment variables to figure out what's going on?
* https://docs.mesa3d.org/egl.html#environment-variables
* https://docs.mesa3d.org/envvars.html#libgl-environment-variables
=> Try to debug linux egl/mesa with envs

.github/workflows/TEST.yml
Since the opengl32.dll provided uses mesa, this might work?
=> Try running offscreen rendering tests with LIBGL_ALWAYS_SOFTWARE=true on windows, and enable debugging

README.md
Added the features of the KorGE engine to the README in order to allow those quickly glancing at the project for the first time from the Github repository to have a broad overview of the game engine's features.
=> Added features list to information section of README

korgw/src/androidMain/kotlin/com/soywiz/korgw/KorgwSurfaceView.kt, korgw/src/commonMain/kotlin/com/soywiz/korev/Events.kt, korgw/src/commonMain/kotlin/com/soywiz/korev/Input.kt, korgw/src/commonMain/kotlin/com/soywiz/korev/gamepad/XInput.kt, korgw/src/commonMain/kotlin/com/soywiz/korgw/GameWindow.kt, korgw/src/commonMain/kotlin/com/soywiz/korgw/x11/X11Joy.kt, korgw/src/iosMacosMain/kotlin/com/soywiz/korgw/DarwinGamePad.kt, korgw/src/jsMain/kotlin/com/soywiz/korgw/DefaultGameWindowJs.kt, korgw/src/jvmMain/kotlin/com/soywiz/korgw/osx/MacosGameController.kt, korgw/src/jvmMain/kotlin/com/soywiz/korgw/win32/XInput.kt, korgw/src/mingwMain/kotlin/com/soywiz/korgw/XInput.kt
Some work simplifying https://github.com/korlibs/korge/issues/1347
=> Simplify gamepad mapping

.github/workflows/TEST.yml, buildSrc/src/main/kotlin/com/soywiz/korlibs/root/RootKorlibsPlugin.kt
It seemed that the "test" sourceSet was not including the assets in the generated test apk
=> Do not require ANDROID_TESTS=true for android connected checks

korte/src/commonMain/kotlin/com/soywiz/korte/DefaultFilters.kt, korte/src/commonTest/kotlin/com/soywiz/korte/TemplateTest.kt
I hope this is ok, I haven't contributed to anything before.
=> Added replace filter (#955)

korau/src/jsMain/kotlin/com/soywiz/korau/sound/HtmlSimpleSound.kt, korau/src/jvmMain/kotlin/com/soywiz/korau/sound/NativeSoundProviderJvm.kt, korau/src/jvmMain/kotlin/com/soywiz/korau/sound/impl/jna/AL.kt, korau/src/jvmMain/kotlin/com/soywiz/korau/sound/impl/jna/JnaSoundProvider.kt, korau/src/mingwMain/kotlin/com/soywiz/korau/sound/Win32NativeSoundProvider.kt, korge-sandbox/src/commonMain/kotlin/samples/MainGpuVectorRendering.kt, korge/src/commonMain/kotlin/com/soywiz/korge/Korge.kt, korgw/src/commonMain/kotlin/com/soywiz/kgl/KmlGlExt.kt, korgw/src/commonMain/kotlin/com/soywiz/kgl/KmlGlProxy.kt, korgw/src/commonMain/kotlin/com/soywiz/korag/AGObjects.kt, korgw/src/commonMain/kotlin/com/soywiz/korag/gl/GLShaderCompiler.kt, korgw/src/commonMain/kotlin/com/soywiz/korag/shader/gl/GlslGenerator.kt, korgw/src/iosMain/kotlin/com/soywiz/korgw/DefaultGameWindowIos.kt, korgw/src/jsMain/kotlin/com/soywiz/korgw/DefaultGameWindowJs.kt, korgw/src/jvmMain/kotlin/com/soywiz/korgw/platform/INativeGL.kt, korim/src/commonMain/kotlin/com/soywiz/korim/format/AVIFInfo.kt, korim/src/commonMain/kotlin/com/soywiz/korim/format/EXIF.kt, korio/src/commonMain/kotlin/com/soywiz/korio/async/AsyncExt.kt, korio/src/commonMain/kotlin/com/soywiz/korio/file/Vfs.kt, korio/src/commonMain/kotlin/com/soywiz/korio/file/std/CatalogVfs.kt, korio/src/commonMain/kotlin/com/soywiz/korio/file/std/MergedVfs.kt, korio/src/commonMain/kotlin/com/soywiz/korio/net/http/HttpPortable.kt, korio/src/commonMain/kotlin/com/soywiz/korio/time/TraceTime.kt, korio/src/jsMain/kotlin/com/soywiz/korio/runtime/node/JsRuntimeNode.kt, korio/src/linuxMain/kotlin/com/soywiz/korio/net/LinuxSSLSocket.kt
First time opening a PR on another persons repo on Github, hope I did it right. Also my (pretty strict) Lint plugin really wants to go crazy on this project 😄
=> Replace Console with Logger almost everywhere

korte/src/jvmAndroidMain/kotlin/com/soywiz/korte/dynamic/ObjectMapper2Native.kt, korte/src/jvmTest/kotlin/com/soywiz/korte/TemplateJvmTest.kt
Fixes https://github.com/korlibs/korge/issues/1406
=> Fixes KorTE's JVM ObjectMapper to not redirect to the field if the getter returned null

korte/src/commonMain/kotlin/com/soywiz/korte/dynamic/Dynamic2.kt, korte/src/commonMain/kotlin/com/soywiz/korte/dynamic/ObjectMapper2.kt, korte/src/jsMain/kotlin/com/soywiz/korte/dynamic/ObjectMapper2Native.kt, korte/src/jvmAndroidMain/kotlin/com/soywiz/korte/dynamic/ObjectMapper2Native.kt, korte/src/jvmTest/kotlin/com/soywiz/korte/TemplateJvmTest.kt, korte/src/nativeMain/kotlin/com/soywiz/korte/dynamic/ObjectMapper2Native.kt
Fixes https://github.com/korlibs/korge/issues/1413
=> Makes ObjectMapper2 interface, make Dynamic2 delegating accessAny to it to support change its behaviour

korge/src/commonMain/kotlin/com/soywiz/korge/render/AgBitmapTextureManager.kt, korge/src/commonMain/kotlin/com/soywiz/korge/render/Texture.kt, korgw/src/commonMain/kotlin/com/soywiz/korag/AGObjects.kt, korgw/src/commonMain/kotlin/com/soywiz/korag/gl/AGOpengl.kt, korim/src/commonMain/kotlin/com/soywiz/korim/bitmap/Bitmap.kt
Should resolve https://github.com/korlibs/korge/issues/1154
=> Make base & max mipmap levels specifiable

.github/workflows/TEST.yml, buildSrc/src/main/kotlin/com/soywiz/korlibs/root/RootKorlibsPlugin.kt
Might help https://github.com/korlibs/korge/pull/1441
=> Run jcmd 0 GC.run on windows before linking tests on CI

klock/src/commonMain/kotlin/com/soywiz/klock/DateFormat.kt, klock/src/commonMain/kotlin/com/soywiz/klock/ISO8601.kt, klock/src/commonMain/kotlin/com/soywiz/klock/PatternDateFormat.kt, klock/src/commonMain/kotlin/com/soywiz/klock/PatternTimeFormat.kt, klock/src/commonMain/kotlin/com/soywiz/klock/TimeFormat.kt, klock/src/commonTest/kotlin/com/soywiz/klock/DateTimeTest.kt
Fixes https://github.com/korlibs/korge/issues/1437
=> DateTime: Support throwing without adjusting for invalid dates

korau/src/androidMain/kotlin/korlibs/audio/sound/AndroidNativeSoundProvider.kt
Fixes the second part of https://github.com/korlibs/korge/issues/1559
The chirping sound was due to writing and reading sound samples in different threads without any synchronization
=> Fixes android Sound, since the deque writer/reader were in different threads and the datastructure was not thread-safe

buildSrc/src/main/kotlin/korlibs/korge/gradle/util/HttpServerTools.kt
Currently wasm files are served with `application/octet-stream` by the builtin `staticHttpServer` task used in `runJs` which causes browser error, i.e. with `WebAssembly.instantiateStreaming`.
I understand that wasm is not supported by Korge yet, but it can still be used in source-sets independent from Korge, i.e. to offload heavy game computations.
=> runJs: correct MIME type for wasm files

buildSrc/src/main/kotlin/korlibs/korge/gradle/util/HttpServerTools.kt
Similar to this [one](https://github.com/korlibs/korge/pull/1562), but now for the [commonly](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types) used JavaScript `*.mjs` module files.
=> runJs: correct MIME type for JavaScript modules

klock/src/darwinMain/kotlin/korlibs/time/darwin/DateExt.kt, klock/src/darwinMain/kotlin/korlibs/time/internal/KlockInternal.kt, klock/src/darwinTest/kotlin/korlibs/time/internal/KlockInternalDarwinTest.kt
Fixes https://github.com/korlibs/korge/issues/1587
=> Fixes localTimezoneOffsetMinutes in apple platforms & adds DateTime.cfAbsoluteTime & DateTime.Companion.fromCFAbsoluteTime

buildSrc/src/main/kotlin/korlibs/korge/gradle/targets/js/Esbuild.kt, buildSrc/src/main/kotlin/korlibs/root/RootKorlibsPlugin.kt
Fixes https://github.com/korlibs/korge/issues/1610
Noticed on https://github.com/korlibs/korge/issues/1580
=> Fixes new esbuild version on windows

klock/src/commonMain/kotlin/korlibs/time/DateFormat.kt, klock/src/commonMain/kotlin/korlibs/time/PatternDateFormat.kt, klock/src/jvmTest/kotlin/korlibs/time/JvmReferenceTest.kt
Fixes https://github.com/korlibs/korge/issues/1632
=> Klock: Fixes Z parsing and adds DateTime.parseLocal as a shortcut for parse(str).local

korge/src/commonMain/kotlin/korlibs/korge/ui/UIButton.kt, korge/src/commonMain/kotlin/korlibs/korge/ui/UIImage.kt, korge/src/commonMain/kotlin/korlibs/korge/view/BlendMode.kt, korge/src/commonMain/kotlin/korlibs/korge/view/StandardViewPropertyProvider.kt, korge/src/commonMain/kotlin/korlibs/korge/view/Text.kt, korge/src/commonMain/kotlin/korlibs/korge/view/TextBlock.kt, korge/src/commonMain/kotlin/korlibs/korge/view/View.kt, korge/src/commonMain/kotlin/korlibs/korge/view/animation/ImageDataView.kt, korge/src/commonMain/kotlin/korlibs/korge/view/filter/Convolute3Filter.kt, korge/src/commonMain/kotlin/korlibs/korge/view/property/ViewProperty.kt, korge/src/jvmMain/kotlin/korlibs/korge/awt/UiEditProperties.kt, korim/src/commonMain/kotlin/korlibs/image/text/TextAlignment.kt, korma/src/commonMain/kotlin/korlibs/math/geom/ScaleMode.kt
=> Improve ViewPropertyProvider, and support ImageDataView.animation selection

buildSrc/src/main/kotlin/korlibs/root/RootKorlibsPlugin.kt, korim/src/darwinMain/kotlin/korlibs/image/format/cg/CGNativeImageFormatProvider.kt, korim/src/jvmMain/kotlin/korlibs/image/format/CoreGraphicsImageFormatProvider.kt, korim/src/jvmTest/kotlin/korlibs/image/format/ImageFormatsNativeTest.kt
This was mistakenly added when trying get wasm working. The idea adding it could allow other tests to continue running and see all the errors at once to report them. But this affected other targets as well, and it was not reverted later.
=> Remove it.ignoreFailures & fixes tests on CI

buildSrc/src/main/kotlin/korlibs/root/RootKorlibsPlugin.kt, docs/korma/geometry/index.md, korma/src/commonMain/kotlin/korlibs/math/geom/Angle.kt, korma/src/commonMain/kotlin/korlibs/math/geom/Orientation.kt, korma/src/commonMain/kotlin/korlibs/math/geom/Vector2.kt, korma/src/commonTest/kotlin/korlibs/math/geom/AngleTest.kt, korma/src/commonTest/kotlin/korlibs/math/geom/OrientationTest.kt, korma/src/commonTest/kotlin/korlibs/math/geom/PointTest.kt
We will need to do the same with Angle.between & Point.angleTo. Maybe alternatively we could provide a UP vector as reference, so it is even more generic.
Fixes https://github.com/korlibs/korge/issues/1062
@Kietyo
=> Supports Orientation, Point.orientation, Point.polar & Angle with Y going down (inverted up vector)

klock/src/commonMain/kotlin/korlibs/time/locale/de.kt, klock/src/commonTest/kotlin/korlibs/time/locale/KlockLocaleTest.kt
I appreciate a review of the code. It feels not right to write down all 32 cases as enum, but german ordinals are partly irregular up to 19. I could not come up with a better solution.
=> De ordinals

korge-sandbox/src/commonMain/kotlin/Main.kt, korge-sandbox/src/commonMain/kotlin/samples/MainUIStacks.kt, korge/src/commonMain/kotlin/korlibs/korge/ui/UIContainerLayouts.kt, korge/src/commonTest/kotlin/korlibs/korge/ui/UIContainerLayoutsTest.kt
Fixes https://github.com/korlibs/korge/issues/1735
=> Improves UIVertical/HorizontalStack behaviour, to compute its size based on their childrens by default

krypto/src/commonMain/kotlin/korlibs/crypto/HMAC.kt, krypto/src/commonTest/kotlin/korlibs/crypto/HMACTest.kt
Fixes #1679 - Add HMAC.hmacSHA512. Output confirmed with https://www.liavaag.org/English/SHA-Generator/HMAC/
=> Fix issue 1679, adding HMAC.hmacSHA512

korau/src/commonMain/kotlin/korlibs/audio/sound/AudioChannel.kt, korau/src/commonMain/kotlin/korlibs/audio/sound/AudioData.kt, korau/src/commonMain/kotlin/korlibs/audio/sound/AudioSamples.kt, korau/src/commonMain/kotlin/korlibs/audio/sound/Sound.kt, korau/src/commonMain/kotlin/korlibs/audio/sound/SoundAudioStream.kt, korau/src/commonTest/kotlin/korlibs.audio.sound/NativeSoundProviderTest.kt, korge-sandbox/src/commonMain/kotlin/Main.kt
Fixes https://github.com/korlibs/korge/issues/1740
=> Fixes base volume in a music Sound not being used when playing it

buildSrc/src/main/kotlin/korlibs/korge/gradle/typedresources/TypedResourcesGenerator.kt, buildSrc/src/main/kotlin/korlibs/korge/gradle/util/UniqueNameGenerator.kt, buildSrc/src/test/kotlin/korlibs/korge/gradle/util/UniqueNameGeneratorTest.kt
Fixes https://github.com/korlibs/korge/issues/1779
=> Fixes .ase slice name generation, to not repeat names that are already used, also cover the case where a nameToVariable generated the same name

korge-sandbox/src/commonMain/kotlin/Main.kt, korge/src/commonMain/kotlin/korlibs/korge/ui/UIFocusManager.kt
Fixes https://github.com/korlibs/korge/issues/1590
=> Fixes Sandbox samples key input interfering with the main dropdown by making the scene container focusable

korge-sandbox/src/commonMain/kotlin/samples/MainCache.kt, korge/src/commonMain/kotlin/korlibs/korge/view/CachedContainer.kt
Adds `CachedContainer.expensiveScaling: Boolean?`, which enables scaling of the content based on the actual window size instead of just the virtual size. Set to `true` by default. 
This fixes part of issue #1748. The default non-bitmap font is still blurry regardless of whether or not it's in a CachedContainer.
In the sandbox:
=> Fix blurry DefaultTtfFontAsBitmap text in CachedContainer when virtual size < window size

korge-core/build.gradle.kts, korge-core/src/jvm/korlibs/wasm/WasmRunJVMJIT.kt, korge-core/test/jvm/korlibs/wasm/WasmJVMTest.kt, korge-core/test/jvm/korlibs/wasm/WasmRunJVMJITExt.kt, korge-core/test/jvm/korlibs/wasm/WastReaderTest.kt
Since it shouldn't be required for production, only to improve debugging
=> Make libs.asm.util be available only on tests

korge/src/js/korlibs/render/DialogInterfaceJs.kt
=> Three-argument document.open()

korge-core/src/common/korlibs/io/async/AsyncExt.kt, korge-core/src/common/korlibs/io/async/PreferSyncIo.kt, korge-core/src/jvmAndroid/korlibs/io/file/std/AsynchronousFileChannelVfs.kt, korge-core/src/jvmAndroid/korlibs/io/file/std/BaseLocalVfsJvm.kt, korge-core/test/common/korlibs/io/file/std/PreferSyncIoTest.kt, korge/src/common/korlibs/korge/Korge.kt
Useful for testing and debugging without losing stack traces without enabling async stacktraces when doing I/O
=> Add and support preferSyncIo in tests & KorGE

korge/src/common/korlibs/korge/ui/UIButton.kt
This fixes the following bug:
- The UIButton's background color doesn't update when setting `enabled` from `false` to `true` (enabling from disabled state)
**Implementation:**
- Improved and slimmed down `UIButton.updatedUIButton`
=> Fix UIButton background color not updating properly

.github/workflows/TEST.yml, buildSrc/src/main/kotlin/korlibs/korge/gradle/targets/Targets.kt, buildSrc/src/main/kotlin/korlibs/modules/Targets.kt, buildSrc/src/main/kotlin/korlibs/root/RootKorlibsPlugin.kt, buildSrc/src/main/kotlin/korlibs/tools.kt, korlibs-time/build.gradle.kts, korlibs-time/src@linux/korlibs/time/Klock.internal.linux.kt, korlibs-time/src@mingw/korlibs/time/Klock.internal.mingw.kt, korlibs-time/src@native/korlibs/time/Klock.internal.native.kt, korlibs-time/test@darwin/korlibs/time/internal/KlockInternalDarwinTest.kt
Includes:
* `linuxX64`, `linuxArm64`
* `macosX64`, `macosArm64`
* `mingwX64`
For now only enabled on `korlibs-time`. Later it will be included to the rest of libraries up to `korge-core`.
See https://github.com/korlibs/korge/issues/2046 for details
=> Re-enable K/N desktop for korlibs-time and try to test using github action matrix

korge-core/src/korlibs/io/net/URL.kt, korge-core/test/korlibs/io/net/URLTest.kt
As per [RFC3986 Secion-3.1](https://datatracker.ietf.org/doc/html/rfc3986#section-3.1) , URL schemes should be case-insensitive, producing only lowercase scheme names for consistency.
This PR closes #2092
=> URL schemes always lowercase fixes issue #2092

korge-core/src/korlibs/io/stream/CharReader.kt, korge-core/test/korlibs/io/net/URLTest.kt, korge-core/test/korlibs/io/stream/CharReaderTest.kt
There was an issue with `CharReaderFromSyncStream`. When attempting to read characters fewer than the specified `chunkSize`, it returns the maximum `chunkSize` data instead. I have set a minimum `chunkSize` limit to 8 because the decoder requires a minimum size of the maximum character size to decode. I believe the maximum character size in bytes is 4 bytes, but for safety, I used 8 bytes. Therefore, if anyone sets the chunkSize to less than 8, it will throw an exception.
* Created two new constants:
```kotlin
companion object {
private const val DEFAULT_CHUNK_SIZE = 1024
private const val MIN_CHUNK_SIZE = 8
}
```
* Check `chunkSize` and throw `IllegalArgumentException` exception if its less than `MIN_CHUNK_SIZE`
```kotlin
init {
if (chunkSize < MIN_CHUNK_SIZE) throw …
```
=> fix CharReaderFromSyncStream read characters less than chunkSize (#2108)

korlibs-crypto/build.gradle.kts
Fixes https://github.com/korlibs/korge/issues/2112
=> Remove time from crypto dependencies (#2112)

korge-core/src@jvm/korlibs/image/awt/AwtExt.kt, korge-core/src@jvm/korlibs/image/awt/AwtNativeImage.kt
BufferedImage itself has internal data buffers that it allocates everytime it's allocated, so this helps reduce memory usage and garbage collection if I'm calling this function often.
For context I have a personal project that grabs the image (a BufferedImage) from HDMI capture device, than sends it over to clients over my network so I can view my surveillance monitor in a different area. Each time I grab the image, I need to convert the image using awtConvertImage so that I can use Korge's Bitmap utils; notably QOI encoding to reduce the size of the data before sending it over the network. Currently, each time awtConvertImage is called, it creates a new BufferedImage.
=> Allow providing pre-allocated BufferedImage for awtConvertImage

korge-core/src/korlibs/image/bitmap/BitmapExt.kt, korge-core/test/korlibs/image/bitmap/BitmapSliceTest.kt
The function putSliceWithBorders is used to create an extruded tileset in LdtkView. The tiles were not extruded correctly into top and bottom left corners. This commit fixes that. It also adds a unit test which reproduces the error.
Incorrectly expanded example of a rectangle:
=> Fix putSliceWithBorders extention function for Bitmap class

korge-core/src@darwin/korlibs/io/file/std/StandardBasePathsDarwin.kt
```
StandardBasePathsDarwin.resourcesFolder:
->
```
These prints were probably left here unintentionally.
=> Remove prints from StandardBasePathsDarwin.kt

korge-core/src/korlibs/audio/sound/PlatformAudioOutput.kt, korge-core/src/korlibs/audio/sound/Sound.kt
Fixes [#1752](https://github.com/korlibs/korge/issues/1752)
=> Add 3D sound API (not implemented yet)

korge/src/korlibs/korge/view/Container.kt, korge/test/korlibs/korge/view/ContainerTest.kt
Current code working in O(n *  c) where `n` is children count and `c` is count we are going to remove.
This is the optimization to O(n)
Also I don't understand how is it possible that child view from __children list has other container as a parent. Is it expected behavior? If not then maybe the code should throw instead of returning everywhere?
=> removeChildAt in O(n) instead of O(n^2) and simplify removeChild

korge-core/src/korlibs/graphics/shader/shaders.kt, korge-core/src/korlibs/korge/render/SDFShaders.kt, korge/src/korlibs/korge/render/RenderContext2DExt.kt, korge/src/korlibs/korge/view/fast/FSprites.kt, korge/src/korlibs/korge/view/filter/DitheringFilter.kt
It seems for me like this change should make shaders more readable and easier to write
=> TEMP with initial value and provide default types for shader functions

korge-core/src/korlibs/graphics/AGObjects.kt
We can just copy data from buffer to buffer instead of making clone when buffers size match.
=> Reduce buffer allocations

korge/src/korlibs/korge/view/View.kt
When I write this code and count myself how much invocations are triggered per second I found that it is ~36
```
addFixedUpdater((1 / 30f).seconds) {
debugOverlay.countTick()
}
```
That happens because sometimes when `accum >= 0.75 * time` we subtract `time` and getting accum < 0 (meaning that we need to wait more next time) But then in the code I'm about to delete we just forgetting that fact.
Maybe better way to fix it is by adding `&& accum > 0` But I actually don't understand what hiccups mean here. And can't see problems which this code solves.
=> Fix fixed updater by removing anti-hiccups code

korge-core/src/korlibs/graphics/AGObjects.kt
It seems pretty reasonable to wrap existing buffer because it provides very convinient methods to manipulate with bytes. Also because the mem property is public buffer content already can be changed from outside but it's impossible to mark this object dirty so I've added upload() method to make it possible
=> Add upload() and wrap methods

buildSrc/src/main/kotlin/korlibs/korge/gradle/processor/KorgeTexturePacker.kt, buildSrc/src/main/kotlin/korlibs/korge/gradle/texpacker/NewTexturePacker.kt, korge-gradle-plugin/src/main/kotlin/korlibs/korge/gradle/processor/KorgeTexturePacker.kt, korge-gradle-plugin/src/main/kotlin/korlibs/korge/gradle/texpacker/NewTexturePacker.kt
Autogenerated atlas texture packing in this pr can be configured through .atlas file in the following manner:
```
#enable-rotation=false
#enable-trimming=false
#padding=1
folder1
folder2
```
=> Configurable atlas textures packing

korge/src/korlibs/korge/view/align/ViewAlignExt.kt
Any reason not to use scaledHeight?
```
var settings = image(resourcesVfs["settings.svg"].readSVG().scaled(1, 1).render()) {
zIndex(3)
position(10, offsetY / 2)
scale(0.2)
}
println("SETTINGS HEIGHT: ${settings.height}") // 400 (incorrect)
println("SETTINGS HEIGHT: ${settings.scaledHeight}") // 80 (correct)
settings.centerYBetween(offsetY, 0.0) // -197 or smth
```
`centerYBetween` does ` - height` (minus) and then here in the snippet it will center the `viewY` on -197
BTW: If this gets merged, the same applies to animators (scaleTo()) too.
=> Fix centering calculations using scaledHeight
